/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.20.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.code.domain.k8s;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * RelabelConfig allows dynamic rewriting of the label set, being applied to samples before ingestion. It defines &#x60;&lt;metric_relabel_configs&gt;&#x60;-section of Prometheus configuration. More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs
 */
@ApiModel(description = "RelabelConfig allows dynamic rewriting of the label set, being applied to samples before ingestion. It defines `<metric_relabel_configs>`-section of Prometheus configuration. More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-03T04:59:34.868Z[Etc/UTC]")
public class ComCoreosMonitoringV1ProbeSpecMetricRelabelings {
  /**
   * Action to perform based on regex matching. Default is &#39;replace&#39;
   */
  @JsonAdapter(ActionEnum.Adapter.class)
  public enum ActionEnum {
    REPLACE("replace"),
    
    KEEP("keep"),
    
    DROP("drop"),
    
    HASHMOD("hashmod"),
    
    LABELMAP("labelmap"),
    
    LABELDROP("labeldrop"),
    
    LABELKEEP("labelkeep");

    private String value;

    ActionEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ActionEnum fromValue(String value) {
      for (ActionEnum b : ActionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ActionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ActionEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ActionEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ActionEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_ACTION = "action";
  @SerializedName(SERIALIZED_NAME_ACTION)
  private ActionEnum action;

  public static final String SERIALIZED_NAME_MODULUS = "modulus";
  @SerializedName(SERIALIZED_NAME_MODULUS)
  private Long modulus;

  public static final String SERIALIZED_NAME_REGEX = "regex";
  @SerializedName(SERIALIZED_NAME_REGEX)
  private String regex;

  public static final String SERIALIZED_NAME_REPLACEMENT = "replacement";
  @SerializedName(SERIALIZED_NAME_REPLACEMENT)
  private String replacement;

  public static final String SERIALIZED_NAME_SEPARATOR = "separator";
  @SerializedName(SERIALIZED_NAME_SEPARATOR)
  private String separator;

  public static final String SERIALIZED_NAME_SOURCE_LABELS = "sourceLabels";
  @SerializedName(SERIALIZED_NAME_SOURCE_LABELS)
  private List<String> sourceLabels = null;

  public static final String SERIALIZED_NAME_TARGET_LABEL = "targetLabel";
  @SerializedName(SERIALIZED_NAME_TARGET_LABEL)
  private String targetLabel;


  public ComCoreosMonitoringV1ProbeSpecMetricRelabelings action(ActionEnum action) {
    
    this.action = action;
    return this;
  }

   /**
   * Action to perform based on regex matching. Default is &#39;replace&#39;
   * @return action
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Action to perform based on regex matching. Default is 'replace'")

  public ActionEnum getAction() {
    return action;
  }


  public void setAction(ActionEnum action) {
    this.action = action;
  }


  public ComCoreosMonitoringV1ProbeSpecMetricRelabelings modulus(Long modulus) {
    
    this.modulus = modulus;
    return this;
  }

   /**
   * Modulus to take of the hash of the source label values.
   * @return modulus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Modulus to take of the hash of the source label values.")

  public Long getModulus() {
    return modulus;
  }


  public void setModulus(Long modulus) {
    this.modulus = modulus;
  }


  public ComCoreosMonitoringV1ProbeSpecMetricRelabelings regex(String regex) {
    
    this.regex = regex;
    return this;
  }

   /**
   * Regular expression against which the extracted value is matched. Default is &#39;(.*)&#39;
   * @return regex
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Regular expression against which the extracted value is matched. Default is '(.*)'")

  public String getRegex() {
    return regex;
  }


  public void setRegex(String regex) {
    this.regex = regex;
  }


  public ComCoreosMonitoringV1ProbeSpecMetricRelabelings replacement(String replacement) {
    
    this.replacement = replacement;
    return this;
  }

   /**
   * Replacement value against which a regex replace is performed if the regular expression matches. Regex capture groups are available. Default is &#39;$1&#39;
   * @return replacement
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Replacement value against which a regex replace is performed if the regular expression matches. Regex capture groups are available. Default is '$1'")

  public String getReplacement() {
    return replacement;
  }


  public void setReplacement(String replacement) {
    this.replacement = replacement;
  }


  public ComCoreosMonitoringV1ProbeSpecMetricRelabelings separator(String separator) {
    
    this.separator = separator;
    return this;
  }

   /**
   * Separator placed between concatenated source label values. default is &#39;;&#39;.
   * @return separator
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Separator placed between concatenated source label values. default is ';'.")

  public String getSeparator() {
    return separator;
  }


  public void setSeparator(String separator) {
    this.separator = separator;
  }


  public ComCoreosMonitoringV1ProbeSpecMetricRelabelings sourceLabels(List<String> sourceLabels) {
    
    this.sourceLabels = sourceLabels;
    return this;
  }

  public ComCoreosMonitoringV1ProbeSpecMetricRelabelings addSourceLabelsItem(String sourceLabelsItem) {
    if (this.sourceLabels == null) {
      this.sourceLabels = new ArrayList<String>();
    }
    this.sourceLabels.add(sourceLabelsItem);
    return this;
  }

   /**
   * The source labels select values from existing labels. Their content is concatenated using the configured separator and matched against the configured regular expression for the replace, keep, and drop actions.
   * @return sourceLabels
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The source labels select values from existing labels. Their content is concatenated using the configured separator and matched against the configured regular expression for the replace, keep, and drop actions.")

  public List<String> getSourceLabels() {
    return sourceLabels;
  }


  public void setSourceLabels(List<String> sourceLabels) {
    this.sourceLabels = sourceLabels;
  }


  public ComCoreosMonitoringV1ProbeSpecMetricRelabelings targetLabel(String targetLabel) {
    
    this.targetLabel = targetLabel;
    return this;
  }

   /**
   * Label to which the resulting value is written in a replace action. It is mandatory for replace actions. Regex capture groups are available.
   * @return targetLabel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Label to which the resulting value is written in a replace action. It is mandatory for replace actions. Regex capture groups are available.")

  public String getTargetLabel() {
    return targetLabel;
  }


  public void setTargetLabel(String targetLabel) {
    this.targetLabel = targetLabel;
  }


  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComCoreosMonitoringV1ProbeSpecMetricRelabelings {\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    modulus: ").append(toIndentedString(modulus)).append("\n");
    sb.append("    regex: ").append(toIndentedString(regex)).append("\n");
    sb.append("    replacement: ").append(toIndentedString(replacement)).append("\n");
    sb.append("    separator: ").append(toIndentedString(separator)).append("\n");
    sb.append("    sourceLabels: ").append(toIndentedString(sourceLabels)).append("\n");
    sb.append("    targetLabel: ").append(toIndentedString(targetLabel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

