/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.20.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.code.domain.k8s;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.example.code.domain.k8s.ComCoreosMonitoringV1PrometheusSpecThanosResources;
import com.example.code.domain.k8s.ComCoreosMonitoringV1ThanosRulerSpecGrpcServerTlsConfig;
import com.example.code.domain.k8s.ComCoreosMonitoringV1ThanosRulerSpecObjectStorageConfig;
import com.example.code.domain.k8s.ComCoreosMonitoringV1ThanosRulerSpecTracingConfig;
import com.example.code.domain.k8s.ComCoreosMonitoringV1ThanosRulerSpecVolumeMounts;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Thanos configuration allows configuring various aspects of a Prometheus server in a Thanos environment.   This section is experimental, it may change significantly without deprecation notice in any release.   This is experimental and may change significantly without backward compatibility in any release.
 */
@ApiModel(description = "Thanos configuration allows configuring various aspects of a Prometheus server in a Thanos environment.   This section is experimental, it may change significantly without deprecation notice in any release.   This is experimental and may change significantly without backward compatibility in any release.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-03T04:59:34.868Z[Etc/UTC]")
public class ComCoreosMonitoringV1PrometheusSpecThanos {
  public static final String SERIALIZED_NAME_BASE_IMAGE = "baseImage";
  @SerializedName(SERIALIZED_NAME_BASE_IMAGE)
  private String baseImage;

  public static final String SERIALIZED_NAME_GRPC_SERVER_TLS_CONFIG = "grpcServerTlsConfig";
  @SerializedName(SERIALIZED_NAME_GRPC_SERVER_TLS_CONFIG)
  private ComCoreosMonitoringV1ThanosRulerSpecGrpcServerTlsConfig grpcServerTlsConfig;

  public static final String SERIALIZED_NAME_IMAGE = "image";
  @SerializedName(SERIALIZED_NAME_IMAGE)
  private String image;

  public static final String SERIALIZED_NAME_LISTEN_LOCAL = "listenLocal";
  @SerializedName(SERIALIZED_NAME_LISTEN_LOCAL)
  private Boolean listenLocal;

  /**
   * LogFormat for Thanos sidecar to be configured with.
   */
  @JsonAdapter(LogFormatEnum.Adapter.class)
  public enum LogFormatEnum {
    EMPTY(""),
    
    LOGFMT("logfmt"),
    
    JSON("json");

    private String value;

    LogFormatEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static LogFormatEnum fromValue(String value) {
      for (LogFormatEnum b : LogFormatEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<LogFormatEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final LogFormatEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public LogFormatEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return LogFormatEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_LOG_FORMAT = "logFormat";
  @SerializedName(SERIALIZED_NAME_LOG_FORMAT)
  private LogFormatEnum logFormat;

  /**
   * LogLevel for Thanos sidecar to be configured with.
   */
  @JsonAdapter(LogLevelEnum.Adapter.class)
  public enum LogLevelEnum {
    EMPTY(""),
    
    DEBUG("debug"),
    
    INFO("info"),
    
    WARN("warn"),
    
    ERROR("error");

    private String value;

    LogLevelEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static LogLevelEnum fromValue(String value) {
      for (LogLevelEnum b : LogLevelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<LogLevelEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final LogLevelEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public LogLevelEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return LogLevelEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_LOG_LEVEL = "logLevel";
  @SerializedName(SERIALIZED_NAME_LOG_LEVEL)
  private LogLevelEnum logLevel;

  public static final String SERIALIZED_NAME_MIN_TIME = "minTime";
  @SerializedName(SERIALIZED_NAME_MIN_TIME)
  private String minTime;

  public static final String SERIALIZED_NAME_OBJECT_STORAGE_CONFIG = "objectStorageConfig";
  @SerializedName(SERIALIZED_NAME_OBJECT_STORAGE_CONFIG)
  private ComCoreosMonitoringV1ThanosRulerSpecObjectStorageConfig objectStorageConfig;

  public static final String SERIALIZED_NAME_OBJECT_STORAGE_CONFIG_FILE = "objectStorageConfigFile";
  @SerializedName(SERIALIZED_NAME_OBJECT_STORAGE_CONFIG_FILE)
  private String objectStorageConfigFile;

  public static final String SERIALIZED_NAME_READY_TIMEOUT = "readyTimeout";
  @SerializedName(SERIALIZED_NAME_READY_TIMEOUT)
  private String readyTimeout;

  public static final String SERIALIZED_NAME_RESOURCES = "resources";
  @SerializedName(SERIALIZED_NAME_RESOURCES)
  private ComCoreosMonitoringV1PrometheusSpecThanosResources resources;

  public static final String SERIALIZED_NAME_SHA = "sha";
  @SerializedName(SERIALIZED_NAME_SHA)
  private String sha;

  public static final String SERIALIZED_NAME_TAG = "tag";
  @SerializedName(SERIALIZED_NAME_TAG)
  private String tag;

  public static final String SERIALIZED_NAME_TRACING_CONFIG = "tracingConfig";
  @SerializedName(SERIALIZED_NAME_TRACING_CONFIG)
  private ComCoreosMonitoringV1ThanosRulerSpecTracingConfig tracingConfig;

  public static final String SERIALIZED_NAME_TRACING_CONFIG_FILE = "tracingConfigFile";
  @SerializedName(SERIALIZED_NAME_TRACING_CONFIG_FILE)
  private String tracingConfigFile;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private String version;

  public static final String SERIALIZED_NAME_VOLUME_MOUNTS = "volumeMounts";
  @SerializedName(SERIALIZED_NAME_VOLUME_MOUNTS)
  private List<ComCoreosMonitoringV1ThanosRulerSpecVolumeMounts> volumeMounts = null;


  public ComCoreosMonitoringV1PrometheusSpecThanos baseImage(String baseImage) {
    
    this.baseImage = baseImage;
    return this;
  }

   /**
   * Thanos base image if other than default. Deprecated: use &#39;image&#39; instead
   * @return baseImage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Thanos base image if other than default. Deprecated: use 'image' instead")

  public String getBaseImage() {
    return baseImage;
  }


  public void setBaseImage(String baseImage) {
    this.baseImage = baseImage;
  }


  public ComCoreosMonitoringV1PrometheusSpecThanos grpcServerTlsConfig(ComCoreosMonitoringV1ThanosRulerSpecGrpcServerTlsConfig grpcServerTlsConfig) {
    
    this.grpcServerTlsConfig = grpcServerTlsConfig;
    return this;
  }

   /**
   * Get grpcServerTlsConfig
   * @return grpcServerTlsConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ComCoreosMonitoringV1ThanosRulerSpecGrpcServerTlsConfig getGrpcServerTlsConfig() {
    return grpcServerTlsConfig;
  }


  public void setGrpcServerTlsConfig(ComCoreosMonitoringV1ThanosRulerSpecGrpcServerTlsConfig grpcServerTlsConfig) {
    this.grpcServerTlsConfig = grpcServerTlsConfig;
  }


  public ComCoreosMonitoringV1PrometheusSpecThanos image(String image) {
    
    this.image = image;
    return this;
  }

   /**
   * Image if specified has precedence over baseImage, tag and sha combinations. Specifying the version is still necessary to ensure the Prometheus Operator knows what version of Thanos is being configured.
   * @return image
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Image if specified has precedence over baseImage, tag and sha combinations. Specifying the version is still necessary to ensure the Prometheus Operator knows what version of Thanos is being configured.")

  public String getImage() {
    return image;
  }


  public void setImage(String image) {
    this.image = image;
  }


  public ComCoreosMonitoringV1PrometheusSpecThanos listenLocal(Boolean listenLocal) {
    
    this.listenLocal = listenLocal;
    return this;
  }

   /**
   * ListenLocal makes the Thanos sidecar listen on loopback, so that it does not bind against the Pod IP.
   * @return listenLocal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ListenLocal makes the Thanos sidecar listen on loopback, so that it does not bind against the Pod IP.")

  public Boolean getListenLocal() {
    return listenLocal;
  }


  public void setListenLocal(Boolean listenLocal) {
    this.listenLocal = listenLocal;
  }


  public ComCoreosMonitoringV1PrometheusSpecThanos logFormat(LogFormatEnum logFormat) {
    
    this.logFormat = logFormat;
    return this;
  }

   /**
   * LogFormat for Thanos sidecar to be configured with.
   * @return logFormat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "LogFormat for Thanos sidecar to be configured with.")

  public LogFormatEnum getLogFormat() {
    return logFormat;
  }


  public void setLogFormat(LogFormatEnum logFormat) {
    this.logFormat = logFormat;
  }


  public ComCoreosMonitoringV1PrometheusSpecThanos logLevel(LogLevelEnum logLevel) {
    
    this.logLevel = logLevel;
    return this;
  }

   /**
   * LogLevel for Thanos sidecar to be configured with.
   * @return logLevel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "LogLevel for Thanos sidecar to be configured with.")

  public LogLevelEnum getLogLevel() {
    return logLevel;
  }


  public void setLogLevel(LogLevelEnum logLevel) {
    this.logLevel = logLevel;
  }


  public ComCoreosMonitoringV1PrometheusSpecThanos minTime(String minTime) {
    
    this.minTime = minTime;
    return this;
  }

   /**
   * MinTime for Thanos sidecar to be configured with. Option can be a constant time in RFC3339 format or time duration relative to current time, such as -1d or 2h45m. Valid duration units are ms, s, m, h, d, w, y.
   * @return minTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "MinTime for Thanos sidecar to be configured with. Option can be a constant time in RFC3339 format or time duration relative to current time, such as -1d or 2h45m. Valid duration units are ms, s, m, h, d, w, y.")

  public String getMinTime() {
    return minTime;
  }


  public void setMinTime(String minTime) {
    this.minTime = minTime;
  }


  public ComCoreosMonitoringV1PrometheusSpecThanos objectStorageConfig(ComCoreosMonitoringV1ThanosRulerSpecObjectStorageConfig objectStorageConfig) {
    
    this.objectStorageConfig = objectStorageConfig;
    return this;
  }

   /**
   * Get objectStorageConfig
   * @return objectStorageConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ComCoreosMonitoringV1ThanosRulerSpecObjectStorageConfig getObjectStorageConfig() {
    return objectStorageConfig;
  }


  public void setObjectStorageConfig(ComCoreosMonitoringV1ThanosRulerSpecObjectStorageConfig objectStorageConfig) {
    this.objectStorageConfig = objectStorageConfig;
  }


  public ComCoreosMonitoringV1PrometheusSpecThanos objectStorageConfigFile(String objectStorageConfigFile) {
    
    this.objectStorageConfigFile = objectStorageConfigFile;
    return this;
  }

   /**
   * ObjectStorageConfigFile specifies the path of the object storage configuration file. When used alongside with ObjectStorageConfig, ObjectStorageConfigFile takes precedence.
   * @return objectStorageConfigFile
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ObjectStorageConfigFile specifies the path of the object storage configuration file. When used alongside with ObjectStorageConfig, ObjectStorageConfigFile takes precedence.")

  public String getObjectStorageConfigFile() {
    return objectStorageConfigFile;
  }


  public void setObjectStorageConfigFile(String objectStorageConfigFile) {
    this.objectStorageConfigFile = objectStorageConfigFile;
  }


  public ComCoreosMonitoringV1PrometheusSpecThanos readyTimeout(String readyTimeout) {
    
    this.readyTimeout = readyTimeout;
    return this;
  }

   /**
   * ReadyTimeout is the maximum time Thanos sidecar will wait for Prometheus to start. Eg 10m
   * @return readyTimeout
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ReadyTimeout is the maximum time Thanos sidecar will wait for Prometheus to start. Eg 10m")

  public String getReadyTimeout() {
    return readyTimeout;
  }


  public void setReadyTimeout(String readyTimeout) {
    this.readyTimeout = readyTimeout;
  }


  public ComCoreosMonitoringV1PrometheusSpecThanos resources(ComCoreosMonitoringV1PrometheusSpecThanosResources resources) {
    
    this.resources = resources;
    return this;
  }

   /**
   * Get resources
   * @return resources
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ComCoreosMonitoringV1PrometheusSpecThanosResources getResources() {
    return resources;
  }


  public void setResources(ComCoreosMonitoringV1PrometheusSpecThanosResources resources) {
    this.resources = resources;
  }


  public ComCoreosMonitoringV1PrometheusSpecThanos sha(String sha) {
    
    this.sha = sha;
    return this;
  }

   /**
   * SHA of Thanos container image to be deployed. Defaults to the value of &#x60;version&#x60;. Similar to a tag, but the SHA explicitly deploys an immutable container image. Version and Tag are ignored if SHA is set. Deprecated: use &#39;image&#39; instead.  The image digest can be specified as part of the image URL.
   * @return sha
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "SHA of Thanos container image to be deployed. Defaults to the value of `version`. Similar to a tag, but the SHA explicitly deploys an immutable container image. Version and Tag are ignored if SHA is set. Deprecated: use 'image' instead.  The image digest can be specified as part of the image URL.")

  public String getSha() {
    return sha;
  }


  public void setSha(String sha) {
    this.sha = sha;
  }


  public ComCoreosMonitoringV1PrometheusSpecThanos tag(String tag) {
    
    this.tag = tag;
    return this;
  }

   /**
   * Tag of Thanos sidecar container image to be deployed. Defaults to the value of &#x60;version&#x60;. Version is ignored if Tag is set. Deprecated: use &#39;image&#39; instead.  The image tag can be specified as part of the image URL.
   * @return tag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Tag of Thanos sidecar container image to be deployed. Defaults to the value of `version`. Version is ignored if Tag is set. Deprecated: use 'image' instead.  The image tag can be specified as part of the image URL.")

  public String getTag() {
    return tag;
  }


  public void setTag(String tag) {
    this.tag = tag;
  }


  public ComCoreosMonitoringV1PrometheusSpecThanos tracingConfig(ComCoreosMonitoringV1ThanosRulerSpecTracingConfig tracingConfig) {
    
    this.tracingConfig = tracingConfig;
    return this;
  }

   /**
   * Get tracingConfig
   * @return tracingConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ComCoreosMonitoringV1ThanosRulerSpecTracingConfig getTracingConfig() {
    return tracingConfig;
  }


  public void setTracingConfig(ComCoreosMonitoringV1ThanosRulerSpecTracingConfig tracingConfig) {
    this.tracingConfig = tracingConfig;
  }


  public ComCoreosMonitoringV1PrometheusSpecThanos tracingConfigFile(String tracingConfigFile) {
    
    this.tracingConfigFile = tracingConfigFile;
    return this;
  }

   /**
   * TracingConfig specifies the path of the tracing configuration file. When used alongside with TracingConfig, TracingConfigFile takes precedence.
   * @return tracingConfigFile
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "TracingConfig specifies the path of the tracing configuration file. When used alongside with TracingConfig, TracingConfigFile takes precedence.")

  public String getTracingConfigFile() {
    return tracingConfigFile;
  }


  public void setTracingConfigFile(String tracingConfigFile) {
    this.tracingConfigFile = tracingConfigFile;
  }


  public ComCoreosMonitoringV1PrometheusSpecThanos version(String version) {
    
    this.version = version;
    return this;
  }

   /**
   * Version describes the version of Thanos to use.
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Version describes the version of Thanos to use.")

  public String getVersion() {
    return version;
  }


  public void setVersion(String version) {
    this.version = version;
  }


  public ComCoreosMonitoringV1PrometheusSpecThanos volumeMounts(List<ComCoreosMonitoringV1ThanosRulerSpecVolumeMounts> volumeMounts) {
    
    this.volumeMounts = volumeMounts;
    return this;
  }

  public ComCoreosMonitoringV1PrometheusSpecThanos addVolumeMountsItem(ComCoreosMonitoringV1ThanosRulerSpecVolumeMounts volumeMountsItem) {
    if (this.volumeMounts == null) {
      this.volumeMounts = new ArrayList<ComCoreosMonitoringV1ThanosRulerSpecVolumeMounts>();
    }
    this.volumeMounts.add(volumeMountsItem);
    return this;
  }

   /**
   * VolumeMounts allows configuration of additional VolumeMounts on the output StatefulSet definition. VolumeMounts specified will be appended to other VolumeMounts in the thanos-sidecar container.
   * @return volumeMounts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "VolumeMounts allows configuration of additional VolumeMounts on the output StatefulSet definition. VolumeMounts specified will be appended to other VolumeMounts in the thanos-sidecar container.")

  public List<ComCoreosMonitoringV1ThanosRulerSpecVolumeMounts> getVolumeMounts() {
    return volumeMounts;
  }


  public void setVolumeMounts(List<ComCoreosMonitoringV1ThanosRulerSpecVolumeMounts> volumeMounts) {
    this.volumeMounts = volumeMounts;
  }


  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComCoreosMonitoringV1PrometheusSpecThanos {\n");
    sb.append("    baseImage: ").append(toIndentedString(baseImage)).append("\n");
    sb.append("    grpcServerTlsConfig: ").append(toIndentedString(grpcServerTlsConfig)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    listenLocal: ").append(toIndentedString(listenLocal)).append("\n");
    sb.append("    logFormat: ").append(toIndentedString(logFormat)).append("\n");
    sb.append("    logLevel: ").append(toIndentedString(logLevel)).append("\n");
    sb.append("    minTime: ").append(toIndentedString(minTime)).append("\n");
    sb.append("    objectStorageConfig: ").append(toIndentedString(objectStorageConfig)).append("\n");
    sb.append("    objectStorageConfigFile: ").append(toIndentedString(objectStorageConfigFile)).append("\n");
    sb.append("    readyTimeout: ").append(toIndentedString(readyTimeout)).append("\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("    sha: ").append(toIndentedString(sha)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    tracingConfig: ").append(toIndentedString(tracingConfig)).append("\n");
    sb.append("    tracingConfigFile: ").append(toIndentedString(tracingConfigFile)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    volumeMounts: ").append(toIndentedString(volumeMounts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

