/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.20.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.code.domain.k8s;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.example.code.domain.k8s.ComCoreosMonitoringV1PodMonitorSpecNamespaceSelector;
import com.example.code.domain.k8s.ComCoreosMonitoringV1PodMonitorSpecPodMetricsEndpoints;
import com.example.code.domain.k8s.ComCoreosMonitoringV1PodMonitorSpecSelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Specification of desired Pod selection for target discovery by Prometheus.
 */
@ApiModel(description = "Specification of desired Pod selection for target discovery by Prometheus.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-03T04:59:34.868Z[Etc/UTC]")
public class ComCoreosMonitoringV1PodMonitorSpec {
  public static final String SERIALIZED_NAME_JOB_LABEL = "jobLabel";
  @SerializedName(SERIALIZED_NAME_JOB_LABEL)
  private String jobLabel;

  public static final String SERIALIZED_NAME_LABEL_LIMIT = "labelLimit";
  @SerializedName(SERIALIZED_NAME_LABEL_LIMIT)
  private Long labelLimit;

  public static final String SERIALIZED_NAME_LABEL_NAME_LENGTH_LIMIT = "labelNameLengthLimit";
  @SerializedName(SERIALIZED_NAME_LABEL_NAME_LENGTH_LIMIT)
  private Long labelNameLengthLimit;

  public static final String SERIALIZED_NAME_LABEL_VALUE_LENGTH_LIMIT = "labelValueLengthLimit";
  @SerializedName(SERIALIZED_NAME_LABEL_VALUE_LENGTH_LIMIT)
  private Long labelValueLengthLimit;

  public static final String SERIALIZED_NAME_NAMESPACE_SELECTOR = "namespaceSelector";
  @SerializedName(SERIALIZED_NAME_NAMESPACE_SELECTOR)
  private ComCoreosMonitoringV1PodMonitorSpecNamespaceSelector namespaceSelector;

  public static final String SERIALIZED_NAME_POD_METRICS_ENDPOINTS = "podMetricsEndpoints";
  @SerializedName(SERIALIZED_NAME_POD_METRICS_ENDPOINTS)
  private List<ComCoreosMonitoringV1PodMonitorSpecPodMetricsEndpoints> podMetricsEndpoints = new ArrayList<ComCoreosMonitoringV1PodMonitorSpecPodMetricsEndpoints>();

  public static final String SERIALIZED_NAME_POD_TARGET_LABELS = "podTargetLabels";
  @SerializedName(SERIALIZED_NAME_POD_TARGET_LABELS)
  private List<String> podTargetLabels = null;

  public static final String SERIALIZED_NAME_SAMPLE_LIMIT = "sampleLimit";
  @SerializedName(SERIALIZED_NAME_SAMPLE_LIMIT)
  private Long sampleLimit;

  public static final String SERIALIZED_NAME_SELECTOR = "selector";
  @SerializedName(SERIALIZED_NAME_SELECTOR)
  private ComCoreosMonitoringV1PodMonitorSpecSelector selector;

  public static final String SERIALIZED_NAME_TARGET_LIMIT = "targetLimit";
  @SerializedName(SERIALIZED_NAME_TARGET_LIMIT)
  private Long targetLimit;


  public ComCoreosMonitoringV1PodMonitorSpec jobLabel(String jobLabel) {
    
    this.jobLabel = jobLabel;
    return this;
  }

   /**
   * The label to use to retrieve the job name from.
   * @return jobLabel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The label to use to retrieve the job name from.")

  public String getJobLabel() {
    return jobLabel;
  }


  public void setJobLabel(String jobLabel) {
    this.jobLabel = jobLabel;
  }


  public ComCoreosMonitoringV1PodMonitorSpec labelLimit(Long labelLimit) {
    
    this.labelLimit = labelLimit;
    return this;
  }

   /**
   * Per-scrape limit on number of labels that will be accepted for a sample. Only valid in Prometheus versions 2.27.0 and newer.
   * @return labelLimit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Per-scrape limit on number of labels that will be accepted for a sample. Only valid in Prometheus versions 2.27.0 and newer.")

  public Long getLabelLimit() {
    return labelLimit;
  }


  public void setLabelLimit(Long labelLimit) {
    this.labelLimit = labelLimit;
  }


  public ComCoreosMonitoringV1PodMonitorSpec labelNameLengthLimit(Long labelNameLengthLimit) {
    
    this.labelNameLengthLimit = labelNameLengthLimit;
    return this;
  }

   /**
   * Per-scrape limit on length of labels name that will be accepted for a sample. Only valid in Prometheus versions 2.27.0 and newer.
   * @return labelNameLengthLimit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Per-scrape limit on length of labels name that will be accepted for a sample. Only valid in Prometheus versions 2.27.0 and newer.")

  public Long getLabelNameLengthLimit() {
    return labelNameLengthLimit;
  }


  public void setLabelNameLengthLimit(Long labelNameLengthLimit) {
    this.labelNameLengthLimit = labelNameLengthLimit;
  }


  public ComCoreosMonitoringV1PodMonitorSpec labelValueLengthLimit(Long labelValueLengthLimit) {
    
    this.labelValueLengthLimit = labelValueLengthLimit;
    return this;
  }

   /**
   * Per-scrape limit on length of labels value that will be accepted for a sample. Only valid in Prometheus versions 2.27.0 and newer.
   * @return labelValueLengthLimit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Per-scrape limit on length of labels value that will be accepted for a sample. Only valid in Prometheus versions 2.27.0 and newer.")

  public Long getLabelValueLengthLimit() {
    return labelValueLengthLimit;
  }


  public void setLabelValueLengthLimit(Long labelValueLengthLimit) {
    this.labelValueLengthLimit = labelValueLengthLimit;
  }


  public ComCoreosMonitoringV1PodMonitorSpec namespaceSelector(ComCoreosMonitoringV1PodMonitorSpecNamespaceSelector namespaceSelector) {
    
    this.namespaceSelector = namespaceSelector;
    return this;
  }

   /**
   * Get namespaceSelector
   * @return namespaceSelector
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ComCoreosMonitoringV1PodMonitorSpecNamespaceSelector getNamespaceSelector() {
    return namespaceSelector;
  }


  public void setNamespaceSelector(ComCoreosMonitoringV1PodMonitorSpecNamespaceSelector namespaceSelector) {
    this.namespaceSelector = namespaceSelector;
  }


  public ComCoreosMonitoringV1PodMonitorSpec podMetricsEndpoints(List<ComCoreosMonitoringV1PodMonitorSpecPodMetricsEndpoints> podMetricsEndpoints) {
    
    this.podMetricsEndpoints = podMetricsEndpoints;
    return this;
  }

  public ComCoreosMonitoringV1PodMonitorSpec addPodMetricsEndpointsItem(ComCoreosMonitoringV1PodMonitorSpecPodMetricsEndpoints podMetricsEndpointsItem) {
    this.podMetricsEndpoints.add(podMetricsEndpointsItem);
    return this;
  }

   /**
   * A list of endpoints allowed as part of this PodMonitor.
   * @return podMetricsEndpoints
  **/
  @ApiModelProperty(required = true, value = "A list of endpoints allowed as part of this PodMonitor.")

  public List<ComCoreosMonitoringV1PodMonitorSpecPodMetricsEndpoints> getPodMetricsEndpoints() {
    return podMetricsEndpoints;
  }


  public void setPodMetricsEndpoints(List<ComCoreosMonitoringV1PodMonitorSpecPodMetricsEndpoints> podMetricsEndpoints) {
    this.podMetricsEndpoints = podMetricsEndpoints;
  }


  public ComCoreosMonitoringV1PodMonitorSpec podTargetLabels(List<String> podTargetLabels) {
    
    this.podTargetLabels = podTargetLabels;
    return this;
  }

  public ComCoreosMonitoringV1PodMonitorSpec addPodTargetLabelsItem(String podTargetLabelsItem) {
    if (this.podTargetLabels == null) {
      this.podTargetLabels = new ArrayList<String>();
    }
    this.podTargetLabels.add(podTargetLabelsItem);
    return this;
  }

   /**
   * PodTargetLabels transfers labels on the Kubernetes Pod onto the target.
   * @return podTargetLabels
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "PodTargetLabels transfers labels on the Kubernetes Pod onto the target.")

  public List<String> getPodTargetLabels() {
    return podTargetLabels;
  }


  public void setPodTargetLabels(List<String> podTargetLabels) {
    this.podTargetLabels = podTargetLabels;
  }


  public ComCoreosMonitoringV1PodMonitorSpec sampleLimit(Long sampleLimit) {
    
    this.sampleLimit = sampleLimit;
    return this;
  }

   /**
   * SampleLimit defines per-scrape limit on number of scraped samples that will be accepted.
   * @return sampleLimit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "SampleLimit defines per-scrape limit on number of scraped samples that will be accepted.")

  public Long getSampleLimit() {
    return sampleLimit;
  }


  public void setSampleLimit(Long sampleLimit) {
    this.sampleLimit = sampleLimit;
  }


  public ComCoreosMonitoringV1PodMonitorSpec selector(ComCoreosMonitoringV1PodMonitorSpecSelector selector) {
    
    this.selector = selector;
    return this;
  }

   /**
   * Get selector
   * @return selector
  **/
  @ApiModelProperty(required = true, value = "")

  public ComCoreosMonitoringV1PodMonitorSpecSelector getSelector() {
    return selector;
  }


  public void setSelector(ComCoreosMonitoringV1PodMonitorSpecSelector selector) {
    this.selector = selector;
  }


  public ComCoreosMonitoringV1PodMonitorSpec targetLimit(Long targetLimit) {
    
    this.targetLimit = targetLimit;
    return this;
  }

   /**
   * TargetLimit defines a limit on the number of scraped targets that will be accepted.
   * @return targetLimit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "TargetLimit defines a limit on the number of scraped targets that will be accepted.")

  public Long getTargetLimit() {
    return targetLimit;
  }


  public void setTargetLimit(Long targetLimit) {
    this.targetLimit = targetLimit;
  }


  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComCoreosMonitoringV1PodMonitorSpec {\n");
    sb.append("    jobLabel: ").append(toIndentedString(jobLabel)).append("\n");
    sb.append("    labelLimit: ").append(toIndentedString(labelLimit)).append("\n");
    sb.append("    labelNameLengthLimit: ").append(toIndentedString(labelNameLengthLimit)).append("\n");
    sb.append("    labelValueLengthLimit: ").append(toIndentedString(labelValueLengthLimit)).append("\n");
    sb.append("    namespaceSelector: ").append(toIndentedString(namespaceSelector)).append("\n");
    sb.append("    podMetricsEndpoints: ").append(toIndentedString(podMetricsEndpoints)).append("\n");
    sb.append("    podTargetLabels: ").append(toIndentedString(podTargetLabels)).append("\n");
    sb.append("    sampleLimit: ").append(toIndentedString(sampleLimit)).append("\n");
    sb.append("    selector: ").append(toIndentedString(selector)).append("\n");
    sb.append("    targetLimit: ").append(toIndentedString(targetLimit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

