/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.20.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.code.domain.k8s;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecApiKey;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHeaders;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecResponders;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * OpsGenieConfig configures notifications via OpsGenie. See https://prometheus.io/docs/alerting/latest/configuration/#opsgenie_config
 */
@ApiModel(description = "OpsGenieConfig configures notifications via OpsGenie. See https://prometheus.io/docs/alerting/latest/configuration/#opsgenie_config")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-03T04:59:34.868Z[Etc/UTC]")
public class ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecOpsgenieConfigs {
  public static final String SERIALIZED_NAME_API_KEY = "apiKey";
  @SerializedName(SERIALIZED_NAME_API_KEY)
  private ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecApiKey apiKey;

  public static final String SERIALIZED_NAME_API_U_R_L = "apiURL";
  @SerializedName(SERIALIZED_NAME_API_U_R_L)
  private String apiURL;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_DETAILS = "details";
  @SerializedName(SERIALIZED_NAME_DETAILS)
  private List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHeaders> details = null;

  public static final String SERIALIZED_NAME_HTTP_CONFIG = "httpConfig";
  @SerializedName(SERIALIZED_NAME_HTTP_CONFIG)
  private ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig httpConfig;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_NOTE = "note";
  @SerializedName(SERIALIZED_NAME_NOTE)
  private String note;

  public static final String SERIALIZED_NAME_PRIORITY = "priority";
  @SerializedName(SERIALIZED_NAME_PRIORITY)
  private String priority;

  public static final String SERIALIZED_NAME_RESPONDERS = "responders";
  @SerializedName(SERIALIZED_NAME_RESPONDERS)
  private List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecResponders> responders = null;

  public static final String SERIALIZED_NAME_SEND_RESOLVED = "sendResolved";
  @SerializedName(SERIALIZED_NAME_SEND_RESOLVED)
  private Boolean sendResolved;

  public static final String SERIALIZED_NAME_SOURCE = "source";
  @SerializedName(SERIALIZED_NAME_SOURCE)
  private String source;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  private String tags;


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecOpsgenieConfigs apiKey(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecApiKey apiKey) {
    
    this.apiKey = apiKey;
    return this;
  }

   /**
   * Get apiKey
   * @return apiKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecApiKey getApiKey() {
    return apiKey;
  }


  public void setApiKey(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecApiKey apiKey) {
    this.apiKey = apiKey;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecOpsgenieConfigs apiURL(String apiURL) {
    
    this.apiURL = apiURL;
    return this;
  }

   /**
   * The URL to send OpsGenie API requests to.
   * @return apiURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The URL to send OpsGenie API requests to.")

  public String getApiURL() {
    return apiURL;
  }


  public void setApiURL(String apiURL) {
    this.apiURL = apiURL;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecOpsgenieConfigs description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Description of the incident.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Description of the incident.")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecOpsgenieConfigs details(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHeaders> details) {
    
    this.details = details;
    return this;
  }

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecOpsgenieConfigs addDetailsItem(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHeaders detailsItem) {
    if (this.details == null) {
      this.details = new ArrayList<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHeaders>();
    }
    this.details.add(detailsItem);
    return this;
  }

   /**
   * A set of arbitrary key/value pairs that provide further detail about the incident.
   * @return details
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A set of arbitrary key/value pairs that provide further detail about the incident.")

  public List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHeaders> getDetails() {
    return details;
  }


  public void setDetails(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHeaders> details) {
    this.details = details;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecOpsgenieConfigs httpConfig(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig httpConfig) {
    
    this.httpConfig = httpConfig;
    return this;
  }

   /**
   * Get httpConfig
   * @return httpConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig getHttpConfig() {
    return httpConfig;
  }


  public void setHttpConfig(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig httpConfig) {
    this.httpConfig = httpConfig;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecOpsgenieConfigs message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * Alert text limited to 130 characters.
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Alert text limited to 130 characters.")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecOpsgenieConfigs note(String note) {
    
    this.note = note;
    return this;
  }

   /**
   * Additional alert note.
   * @return note
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Additional alert note.")

  public String getNote() {
    return note;
  }


  public void setNote(String note) {
    this.note = note;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecOpsgenieConfigs priority(String priority) {
    
    this.priority = priority;
    return this;
  }

   /**
   * Priority level of alert. Possible values are P1, P2, P3, P4, and P5.
   * @return priority
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Priority level of alert. Possible values are P1, P2, P3, P4, and P5.")

  public String getPriority() {
    return priority;
  }


  public void setPriority(String priority) {
    this.priority = priority;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecOpsgenieConfigs responders(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecResponders> responders) {
    
    this.responders = responders;
    return this;
  }

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecOpsgenieConfigs addRespondersItem(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecResponders respondersItem) {
    if (this.responders == null) {
      this.responders = new ArrayList<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecResponders>();
    }
    this.responders.add(respondersItem);
    return this;
  }

   /**
   * List of responders responsible for notifications.
   * @return responders
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of responders responsible for notifications.")

  public List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecResponders> getResponders() {
    return responders;
  }


  public void setResponders(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecResponders> responders) {
    this.responders = responders;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecOpsgenieConfigs sendResolved(Boolean sendResolved) {
    
    this.sendResolved = sendResolved;
    return this;
  }

   /**
   * Whether or not to notify about resolved alerts.
   * @return sendResolved
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether or not to notify about resolved alerts.")

  public Boolean getSendResolved() {
    return sendResolved;
  }


  public void setSendResolved(Boolean sendResolved) {
    this.sendResolved = sendResolved;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecOpsgenieConfigs source(String source) {
    
    this.source = source;
    return this;
  }

   /**
   * Backlink to the sender of the notification.
   * @return source
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Backlink to the sender of the notification.")

  public String getSource() {
    return source;
  }


  public void setSource(String source) {
    this.source = source;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecOpsgenieConfigs tags(String tags) {
    
    this.tags = tags;
    return this;
  }

   /**
   * Comma separated list of tags attached to the notifications.
   * @return tags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Comma separated list of tags attached to the notifications.")

  public String getTags() {
    return tags;
  }


  public void setTags(String tags) {
    this.tags = tags;
  }


  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecOpsgenieConfigs {\n");
    sb.append("    apiKey: ").append(toIndentedString(apiKey)).append("\n");
    sb.append("    apiURL: ").append(toIndentedString(apiURL)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    httpConfig: ").append(toIndentedString(httpConfig)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    responders: ").append(toIndentedString(responders)).append("\n");
    sb.append("    sendResolved: ").append(toIndentedString(sendResolved)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

