/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.20.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.code.domain.k8s;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHeaders;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerDutyImageConfigs;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerDutyLinkConfigs;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecRoutingKey;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecServiceKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * PagerDutyConfig configures notifications via PagerDuty. See https://prometheus.io/docs/alerting/latest/configuration/#pagerduty_config
 */
@ApiModel(description = "PagerDutyConfig configures notifications via PagerDuty. See https://prometheus.io/docs/alerting/latest/configuration/#pagerduty_config")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-03T04:59:34.868Z[Etc/UTC]")
public class ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs {
  public static final String SERIALIZED_NAME_PROPERTY_CLASS = "class";
  @SerializedName(SERIALIZED_NAME_PROPERTY_CLASS)
  private String propertyClass;

  public static final String SERIALIZED_NAME_CLIENT = "client";
  @SerializedName(SERIALIZED_NAME_CLIENT)
  private String client;

  public static final String SERIALIZED_NAME_CLIENT_U_R_L = "clientURL";
  @SerializedName(SERIALIZED_NAME_CLIENT_U_R_L)
  private String clientURL;

  public static final String SERIALIZED_NAME_COMPONENT = "component";
  @SerializedName(SERIALIZED_NAME_COMPONENT)
  private String component;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_DETAILS = "details";
  @SerializedName(SERIALIZED_NAME_DETAILS)
  private List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHeaders> details = null;

  public static final String SERIALIZED_NAME_GROUP = "group";
  @SerializedName(SERIALIZED_NAME_GROUP)
  private String group;

  public static final String SERIALIZED_NAME_HTTP_CONFIG = "httpConfig";
  @SerializedName(SERIALIZED_NAME_HTTP_CONFIG)
  private ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig httpConfig;

  public static final String SERIALIZED_NAME_PAGER_DUTY_IMAGE_CONFIGS = "pagerDutyImageConfigs";
  @SerializedName(SERIALIZED_NAME_PAGER_DUTY_IMAGE_CONFIGS)
  private List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerDutyImageConfigs> pagerDutyImageConfigs = null;

  public static final String SERIALIZED_NAME_PAGER_DUTY_LINK_CONFIGS = "pagerDutyLinkConfigs";
  @SerializedName(SERIALIZED_NAME_PAGER_DUTY_LINK_CONFIGS)
  private List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerDutyLinkConfigs> pagerDutyLinkConfigs = null;

  public static final String SERIALIZED_NAME_ROUTING_KEY = "routingKey";
  @SerializedName(SERIALIZED_NAME_ROUTING_KEY)
  private ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecRoutingKey routingKey;

  public static final String SERIALIZED_NAME_SEND_RESOLVED = "sendResolved";
  @SerializedName(SERIALIZED_NAME_SEND_RESOLVED)
  private Boolean sendResolved;

  public static final String SERIALIZED_NAME_SERVICE_KEY = "serviceKey";
  @SerializedName(SERIALIZED_NAME_SERVICE_KEY)
  private ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecServiceKey serviceKey;

  public static final String SERIALIZED_NAME_SEVERITY = "severity";
  @SerializedName(SERIALIZED_NAME_SEVERITY)
  private String severity;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs propertyClass(String propertyClass) {
    
    this.propertyClass = propertyClass;
    return this;
  }

   /**
   * The class/type of the event.
   * @return propertyClass
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The class/type of the event.")

  public String getPropertyClass() {
    return propertyClass;
  }


  public void setPropertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs client(String client) {
    
    this.client = client;
    return this;
  }

   /**
   * Client identification.
   * @return client
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Client identification.")

  public String getClient() {
    return client;
  }


  public void setClient(String client) {
    this.client = client;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs clientURL(String clientURL) {
    
    this.clientURL = clientURL;
    return this;
  }

   /**
   * Backlink to the sender of notification.
   * @return clientURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Backlink to the sender of notification.")

  public String getClientURL() {
    return clientURL;
  }


  public void setClientURL(String clientURL) {
    this.clientURL = clientURL;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs component(String component) {
    
    this.component = component;
    return this;
  }

   /**
   * The part or component of the affected system that is broken.
   * @return component
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The part or component of the affected system that is broken.")

  public String getComponent() {
    return component;
  }


  public void setComponent(String component) {
    this.component = component;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Description of the incident.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Description of the incident.")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs details(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHeaders> details) {
    
    this.details = details;
    return this;
  }

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs addDetailsItem(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHeaders detailsItem) {
    if (this.details == null) {
      this.details = new ArrayList<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHeaders>();
    }
    this.details.add(detailsItem);
    return this;
  }

   /**
   * Arbitrary key/value pairs that provide further detail about the incident.
   * @return details
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Arbitrary key/value pairs that provide further detail about the incident.")

  public List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHeaders> getDetails() {
    return details;
  }


  public void setDetails(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHeaders> details) {
    this.details = details;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs group(String group) {
    
    this.group = group;
    return this;
  }

   /**
   * A cluster or grouping of sources.
   * @return group
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A cluster or grouping of sources.")

  public String getGroup() {
    return group;
  }


  public void setGroup(String group) {
    this.group = group;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs httpConfig(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig httpConfig) {
    
    this.httpConfig = httpConfig;
    return this;
  }

   /**
   * Get httpConfig
   * @return httpConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig getHttpConfig() {
    return httpConfig;
  }


  public void setHttpConfig(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig httpConfig) {
    this.httpConfig = httpConfig;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs pagerDutyImageConfigs(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerDutyImageConfigs> pagerDutyImageConfigs) {
    
    this.pagerDutyImageConfigs = pagerDutyImageConfigs;
    return this;
  }

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs addPagerDutyImageConfigsItem(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerDutyImageConfigs pagerDutyImageConfigsItem) {
    if (this.pagerDutyImageConfigs == null) {
      this.pagerDutyImageConfigs = new ArrayList<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerDutyImageConfigs>();
    }
    this.pagerDutyImageConfigs.add(pagerDutyImageConfigsItem);
    return this;
  }

   /**
   * A list of image details to attach that provide further detail about an incident.
   * @return pagerDutyImageConfigs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of image details to attach that provide further detail about an incident.")

  public List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerDutyImageConfigs> getPagerDutyImageConfigs() {
    return pagerDutyImageConfigs;
  }


  public void setPagerDutyImageConfigs(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerDutyImageConfigs> pagerDutyImageConfigs) {
    this.pagerDutyImageConfigs = pagerDutyImageConfigs;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs pagerDutyLinkConfigs(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerDutyLinkConfigs> pagerDutyLinkConfigs) {
    
    this.pagerDutyLinkConfigs = pagerDutyLinkConfigs;
    return this;
  }

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs addPagerDutyLinkConfigsItem(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerDutyLinkConfigs pagerDutyLinkConfigsItem) {
    if (this.pagerDutyLinkConfigs == null) {
      this.pagerDutyLinkConfigs = new ArrayList<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerDutyLinkConfigs>();
    }
    this.pagerDutyLinkConfigs.add(pagerDutyLinkConfigsItem);
    return this;
  }

   /**
   * A list of link details to attach that provide further detail about an incident.
   * @return pagerDutyLinkConfigs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of link details to attach that provide further detail about an incident.")

  public List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerDutyLinkConfigs> getPagerDutyLinkConfigs() {
    return pagerDutyLinkConfigs;
  }


  public void setPagerDutyLinkConfigs(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerDutyLinkConfigs> pagerDutyLinkConfigs) {
    this.pagerDutyLinkConfigs = pagerDutyLinkConfigs;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs routingKey(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecRoutingKey routingKey) {
    
    this.routingKey = routingKey;
    return this;
  }

   /**
   * Get routingKey
   * @return routingKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecRoutingKey getRoutingKey() {
    return routingKey;
  }


  public void setRoutingKey(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecRoutingKey routingKey) {
    this.routingKey = routingKey;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs sendResolved(Boolean sendResolved) {
    
    this.sendResolved = sendResolved;
    return this;
  }

   /**
   * Whether or not to notify about resolved alerts.
   * @return sendResolved
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether or not to notify about resolved alerts.")

  public Boolean getSendResolved() {
    return sendResolved;
  }


  public void setSendResolved(Boolean sendResolved) {
    this.sendResolved = sendResolved;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs serviceKey(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecServiceKey serviceKey) {
    
    this.serviceKey = serviceKey;
    return this;
  }

   /**
   * Get serviceKey
   * @return serviceKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecServiceKey getServiceKey() {
    return serviceKey;
  }


  public void setServiceKey(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecServiceKey serviceKey) {
    this.serviceKey = serviceKey;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs severity(String severity) {
    
    this.severity = severity;
    return this;
  }

   /**
   * Severity of the incident.
   * @return severity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Severity of the incident.")

  public String getSeverity() {
    return severity;
  }


  public void setSeverity(String severity) {
    this.severity = severity;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * The URL to send requests to.
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The URL to send requests to.")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs {\n");
    sb.append("    propertyClass: ").append(toIndentedString(propertyClass)).append("\n");
    sb.append("    client: ").append(toIndentedString(client)).append("\n");
    sb.append("    clientURL: ").append(toIndentedString(clientURL)).append("\n");
    sb.append("    component: ").append(toIndentedString(component)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    httpConfig: ").append(toIndentedString(httpConfig)).append("\n");
    sb.append("    pagerDutyImageConfigs: ").append(toIndentedString(pagerDutyImageConfigs)).append("\n");
    sb.append("    pagerDutyLinkConfigs: ").append(toIndentedString(pagerDutyLinkConfigs)).append("\n");
    sb.append("    routingKey: ").append(toIndentedString(routingKey)).append("\n");
    sb.append("    sendResolved: ").append(toIndentedString(sendResolved)).append("\n");
    sb.append("    serviceKey: ").append(toIndentedString(serviceKey)).append("\n");
    sb.append("    severity: ").append(toIndentedString(severity)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

