/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.20.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.code.domain.k8s;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecEmailConfigs;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecOpsgenieConfigs;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPushoverConfigs;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSnsConfigs;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecVictoropsConfigs;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecWebhookConfigs;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecWechatConfigs;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Receiver defines one or more notification integrations.
 */
@ApiModel(description = "Receiver defines one or more notification integrations.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-03T04:59:34.868Z[Etc/UTC]")
public class ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecReceivers {
  public static final String SERIALIZED_NAME_EMAIL_CONFIGS = "emailConfigs";
  @SerializedName(SERIALIZED_NAME_EMAIL_CONFIGS)
  private List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecEmailConfigs> emailConfigs = null;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_OPSGENIE_CONFIGS = "opsgenieConfigs";
  @SerializedName(SERIALIZED_NAME_OPSGENIE_CONFIGS)
  private List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecOpsgenieConfigs> opsgenieConfigs = null;

  public static final String SERIALIZED_NAME_PAGERDUTY_CONFIGS = "pagerdutyConfigs";
  @SerializedName(SERIALIZED_NAME_PAGERDUTY_CONFIGS)
  private List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs> pagerdutyConfigs = null;

  public static final String SERIALIZED_NAME_PUSHOVER_CONFIGS = "pushoverConfigs";
  @SerializedName(SERIALIZED_NAME_PUSHOVER_CONFIGS)
  private List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPushoverConfigs> pushoverConfigs = null;

  public static final String SERIALIZED_NAME_SLACK_CONFIGS = "slackConfigs";
  @SerializedName(SERIALIZED_NAME_SLACK_CONFIGS)
  private List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs> slackConfigs = null;

  public static final String SERIALIZED_NAME_SNS_CONFIGS = "snsConfigs";
  @SerializedName(SERIALIZED_NAME_SNS_CONFIGS)
  private List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSnsConfigs> snsConfigs = null;

  public static final String SERIALIZED_NAME_VICTOROPS_CONFIGS = "victoropsConfigs";
  @SerializedName(SERIALIZED_NAME_VICTOROPS_CONFIGS)
  private List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecVictoropsConfigs> victoropsConfigs = null;

  public static final String SERIALIZED_NAME_WEBHOOK_CONFIGS = "webhookConfigs";
  @SerializedName(SERIALIZED_NAME_WEBHOOK_CONFIGS)
  private List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecWebhookConfigs> webhookConfigs = null;

  public static final String SERIALIZED_NAME_WECHAT_CONFIGS = "wechatConfigs";
  @SerializedName(SERIALIZED_NAME_WECHAT_CONFIGS)
  private List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecWechatConfigs> wechatConfigs = null;


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecReceivers emailConfigs(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecEmailConfigs> emailConfigs) {
    
    this.emailConfigs = emailConfigs;
    return this;
  }

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecReceivers addEmailConfigsItem(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecEmailConfigs emailConfigsItem) {
    if (this.emailConfigs == null) {
      this.emailConfigs = new ArrayList<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecEmailConfigs>();
    }
    this.emailConfigs.add(emailConfigsItem);
    return this;
  }

   /**
   * List of Email configurations.
   * @return emailConfigs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of Email configurations.")

  public List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecEmailConfigs> getEmailConfigs() {
    return emailConfigs;
  }


  public void setEmailConfigs(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecEmailConfigs> emailConfigs) {
    this.emailConfigs = emailConfigs;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecReceivers name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the receiver. Must be unique across all items from the list.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name of the receiver. Must be unique across all items from the list.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecReceivers opsgenieConfigs(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecOpsgenieConfigs> opsgenieConfigs) {
    
    this.opsgenieConfigs = opsgenieConfigs;
    return this;
  }

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecReceivers addOpsgenieConfigsItem(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecOpsgenieConfigs opsgenieConfigsItem) {
    if (this.opsgenieConfigs == null) {
      this.opsgenieConfigs = new ArrayList<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecOpsgenieConfigs>();
    }
    this.opsgenieConfigs.add(opsgenieConfigsItem);
    return this;
  }

   /**
   * List of OpsGenie configurations.
   * @return opsgenieConfigs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of OpsGenie configurations.")

  public List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecOpsgenieConfigs> getOpsgenieConfigs() {
    return opsgenieConfigs;
  }


  public void setOpsgenieConfigs(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecOpsgenieConfigs> opsgenieConfigs) {
    this.opsgenieConfigs = opsgenieConfigs;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecReceivers pagerdutyConfigs(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs> pagerdutyConfigs) {
    
    this.pagerdutyConfigs = pagerdutyConfigs;
    return this;
  }

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecReceivers addPagerdutyConfigsItem(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs pagerdutyConfigsItem) {
    if (this.pagerdutyConfigs == null) {
      this.pagerdutyConfigs = new ArrayList<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs>();
    }
    this.pagerdutyConfigs.add(pagerdutyConfigsItem);
    return this;
  }

   /**
   * List of PagerDuty configurations.
   * @return pagerdutyConfigs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of PagerDuty configurations.")

  public List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs> getPagerdutyConfigs() {
    return pagerdutyConfigs;
  }


  public void setPagerdutyConfigs(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPagerdutyConfigs> pagerdutyConfigs) {
    this.pagerdutyConfigs = pagerdutyConfigs;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecReceivers pushoverConfigs(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPushoverConfigs> pushoverConfigs) {
    
    this.pushoverConfigs = pushoverConfigs;
    return this;
  }

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecReceivers addPushoverConfigsItem(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPushoverConfigs pushoverConfigsItem) {
    if (this.pushoverConfigs == null) {
      this.pushoverConfigs = new ArrayList<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPushoverConfigs>();
    }
    this.pushoverConfigs.add(pushoverConfigsItem);
    return this;
  }

   /**
   * List of Pushover configurations.
   * @return pushoverConfigs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of Pushover configurations.")

  public List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPushoverConfigs> getPushoverConfigs() {
    return pushoverConfigs;
  }


  public void setPushoverConfigs(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecPushoverConfigs> pushoverConfigs) {
    this.pushoverConfigs = pushoverConfigs;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecReceivers slackConfigs(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs> slackConfigs) {
    
    this.slackConfigs = slackConfigs;
    return this;
  }

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecReceivers addSlackConfigsItem(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs slackConfigsItem) {
    if (this.slackConfigs == null) {
      this.slackConfigs = new ArrayList<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs>();
    }
    this.slackConfigs.add(slackConfigsItem);
    return this;
  }

   /**
   * List of Slack configurations.
   * @return slackConfigs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of Slack configurations.")

  public List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs> getSlackConfigs() {
    return slackConfigs;
  }


  public void setSlackConfigs(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs> slackConfigs) {
    this.slackConfigs = slackConfigs;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecReceivers snsConfigs(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSnsConfigs> snsConfigs) {
    
    this.snsConfigs = snsConfigs;
    return this;
  }

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecReceivers addSnsConfigsItem(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSnsConfigs snsConfigsItem) {
    if (this.snsConfigs == null) {
      this.snsConfigs = new ArrayList<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSnsConfigs>();
    }
    this.snsConfigs.add(snsConfigsItem);
    return this;
  }

   /**
   * List of SNS configurations
   * @return snsConfigs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of SNS configurations")

  public List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSnsConfigs> getSnsConfigs() {
    return snsConfigs;
  }


  public void setSnsConfigs(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSnsConfigs> snsConfigs) {
    this.snsConfigs = snsConfigs;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecReceivers victoropsConfigs(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecVictoropsConfigs> victoropsConfigs) {
    
    this.victoropsConfigs = victoropsConfigs;
    return this;
  }

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecReceivers addVictoropsConfigsItem(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecVictoropsConfigs victoropsConfigsItem) {
    if (this.victoropsConfigs == null) {
      this.victoropsConfigs = new ArrayList<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecVictoropsConfigs>();
    }
    this.victoropsConfigs.add(victoropsConfigsItem);
    return this;
  }

   /**
   * List of VictorOps configurations.
   * @return victoropsConfigs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of VictorOps configurations.")

  public List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecVictoropsConfigs> getVictoropsConfigs() {
    return victoropsConfigs;
  }


  public void setVictoropsConfigs(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecVictoropsConfigs> victoropsConfigs) {
    this.victoropsConfigs = victoropsConfigs;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecReceivers webhookConfigs(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecWebhookConfigs> webhookConfigs) {
    
    this.webhookConfigs = webhookConfigs;
    return this;
  }

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecReceivers addWebhookConfigsItem(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecWebhookConfigs webhookConfigsItem) {
    if (this.webhookConfigs == null) {
      this.webhookConfigs = new ArrayList<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecWebhookConfigs>();
    }
    this.webhookConfigs.add(webhookConfigsItem);
    return this;
  }

   /**
   * List of webhook configurations.
   * @return webhookConfigs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of webhook configurations.")

  public List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecWebhookConfigs> getWebhookConfigs() {
    return webhookConfigs;
  }


  public void setWebhookConfigs(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecWebhookConfigs> webhookConfigs) {
    this.webhookConfigs = webhookConfigs;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecReceivers wechatConfigs(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecWechatConfigs> wechatConfigs) {
    
    this.wechatConfigs = wechatConfigs;
    return this;
  }

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecReceivers addWechatConfigsItem(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecWechatConfigs wechatConfigsItem) {
    if (this.wechatConfigs == null) {
      this.wechatConfigs = new ArrayList<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecWechatConfigs>();
    }
    this.wechatConfigs.add(wechatConfigsItem);
    return this;
  }

   /**
   * List of WeChat configurations.
   * @return wechatConfigs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of WeChat configurations.")

  public List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecWechatConfigs> getWechatConfigs() {
    return wechatConfigs;
  }


  public void setWechatConfigs(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecWechatConfigs> wechatConfigs) {
    this.wechatConfigs = wechatConfigs;
  }


  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecReceivers {\n");
    sb.append("    emailConfigs: ").append(toIndentedString(emailConfigs)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    opsgenieConfigs: ").append(toIndentedString(opsgenieConfigs)).append("\n");
    sb.append("    pagerdutyConfigs: ").append(toIndentedString(pagerdutyConfigs)).append("\n");
    sb.append("    pushoverConfigs: ").append(toIndentedString(pushoverConfigs)).append("\n");
    sb.append("    slackConfigs: ").append(toIndentedString(slackConfigs)).append("\n");
    sb.append("    snsConfigs: ").append(toIndentedString(snsConfigs)).append("\n");
    sb.append("    victoropsConfigs: ").append(toIndentedString(victoropsConfigs)).append("\n");
    sb.append("    webhookConfigs: ").append(toIndentedString(webhookConfigs)).append("\n");
    sb.append("    wechatConfigs: ").append(toIndentedString(wechatConfigs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

