/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.20.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.code.domain.k8s;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSigv4AccessKey;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSigv4SecretKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Sigv4 allows to configures AWS&#39;s Signature Verification 4
 */
@ApiModel(description = "Sigv4 allows to configures AWS's Signature Verification 4")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-03T04:59:34.868Z[Etc/UTC]")
public class ComCoreosMonitoringV1PrometheusSpecSigv4 {
  public static final String SERIALIZED_NAME_ACCESS_KEY = "accessKey";
  @SerializedName(SERIALIZED_NAME_ACCESS_KEY)
  private ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSigv4AccessKey accessKey;

  public static final String SERIALIZED_NAME_PROFILE = "profile";
  @SerializedName(SERIALIZED_NAME_PROFILE)
  private String profile;

  public static final String SERIALIZED_NAME_REGION = "region";
  @SerializedName(SERIALIZED_NAME_REGION)
  private String region;

  public static final String SERIALIZED_NAME_ROLE_ARN = "roleArn";
  @SerializedName(SERIALIZED_NAME_ROLE_ARN)
  private String roleArn;

  public static final String SERIALIZED_NAME_SECRET_KEY = "secretKey";
  @SerializedName(SERIALIZED_NAME_SECRET_KEY)
  private ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSigv4SecretKey secretKey;


  public ComCoreosMonitoringV1PrometheusSpecSigv4 accessKey(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSigv4AccessKey accessKey) {
    
    this.accessKey = accessKey;
    return this;
  }

   /**
   * Get accessKey
   * @return accessKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSigv4AccessKey getAccessKey() {
    return accessKey;
  }


  public void setAccessKey(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSigv4AccessKey accessKey) {
    this.accessKey = accessKey;
  }


  public ComCoreosMonitoringV1PrometheusSpecSigv4 profile(String profile) {
    
    this.profile = profile;
    return this;
  }

   /**
   * Profile is the named AWS profile used to authenticate.
   * @return profile
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Profile is the named AWS profile used to authenticate.")

  public String getProfile() {
    return profile;
  }


  public void setProfile(String profile) {
    this.profile = profile;
  }


  public ComCoreosMonitoringV1PrometheusSpecSigv4 region(String region) {
    
    this.region = region;
    return this;
  }

   /**
   * Region is the AWS region. If blank, the region from the default credentials chain used.
   * @return region
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Region is the AWS region. If blank, the region from the default credentials chain used.")

  public String getRegion() {
    return region;
  }


  public void setRegion(String region) {
    this.region = region;
  }


  public ComCoreosMonitoringV1PrometheusSpecSigv4 roleArn(String roleArn) {
    
    this.roleArn = roleArn;
    return this;
  }

   /**
   * RoleArn is the named AWS profile used to authenticate.
   * @return roleArn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "RoleArn is the named AWS profile used to authenticate.")

  public String getRoleArn() {
    return roleArn;
  }


  public void setRoleArn(String roleArn) {
    this.roleArn = roleArn;
  }


  public ComCoreosMonitoringV1PrometheusSpecSigv4 secretKey(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSigv4SecretKey secretKey) {
    
    this.secretKey = secretKey;
    return this;
  }

   /**
   * Get secretKey
   * @return secretKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSigv4SecretKey getSecretKey() {
    return secretKey;
  }


  public void setSecretKey(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSigv4SecretKey secretKey) {
    this.secretKey = secretKey;
  }


  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComCoreosMonitoringV1PrometheusSpecSigv4 {\n");
    sb.append("    accessKey: ").append(toIndentedString(accessKey)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    roleArn: ").append(toIndentedString(roleArn)).append("\n");
    sb.append("    secretKey: ").append(toIndentedString(secretKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

