/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.20.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.code.domain.k8s;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSigv4;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * SNSConfig configures notifications via AWS SNS. See https://prometheus.io/docs/alerting/latest/configuration/#sns_configs
 */
@ApiModel(description = "SNSConfig configures notifications via AWS SNS. See https://prometheus.io/docs/alerting/latest/configuration/#sns_configs")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-03T04:59:34.868Z[Etc/UTC]")
public class ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSnsConfigs {
  public static final String SERIALIZED_NAME_API_U_R_L = "apiURL";
  @SerializedName(SERIALIZED_NAME_API_U_R_L)
  private String apiURL;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  private Map<String, String> attributes = null;

  public static final String SERIALIZED_NAME_HTTP_CONFIG = "httpConfig";
  @SerializedName(SERIALIZED_NAME_HTTP_CONFIG)
  private ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig httpConfig;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_PHONE_NUMBER = "phoneNumber";
  @SerializedName(SERIALIZED_NAME_PHONE_NUMBER)
  private String phoneNumber;

  public static final String SERIALIZED_NAME_SEND_RESOLVED = "sendResolved";
  @SerializedName(SERIALIZED_NAME_SEND_RESOLVED)
  private Boolean sendResolved;

  public static final String SERIALIZED_NAME_SIGV4 = "sigv4";
  @SerializedName(SERIALIZED_NAME_SIGV4)
  private ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSigv4 sigv4;

  public static final String SERIALIZED_NAME_SUBJECT = "subject";
  @SerializedName(SERIALIZED_NAME_SUBJECT)
  private String subject;

  public static final String SERIALIZED_NAME_TARGET_A_R_N = "targetARN";
  @SerializedName(SERIALIZED_NAME_TARGET_A_R_N)
  private String targetARN;

  public static final String SERIALIZED_NAME_TOPIC_A_R_N = "topicARN";
  @SerializedName(SERIALIZED_NAME_TOPIC_A_R_N)
  private String topicARN;


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSnsConfigs apiURL(String apiURL) {
    
    this.apiURL = apiURL;
    return this;
  }

   /**
   * The SNS API URL i.e. https://sns.us-east-2.amazonaws.com. If not specified, the SNS API URL from the SNS SDK will be used.
   * @return apiURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The SNS API URL i.e. https://sns.us-east-2.amazonaws.com. If not specified, the SNS API URL from the SNS SDK will be used.")

  public String getApiURL() {
    return apiURL;
  }


  public void setApiURL(String apiURL) {
    this.apiURL = apiURL;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSnsConfigs attributes(Map<String, String> attributes) {
    
    this.attributes = attributes;
    return this;
  }

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSnsConfigs putAttributesItem(String key, String attributesItem) {
    if (this.attributes == null) {
      this.attributes = new HashMap<String, String>();
    }
    this.attributes.put(key, attributesItem);
    return this;
  }

   /**
   * SNS message attributes.
   * @return attributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "SNS message attributes.")

  public Map<String, String> getAttributes() {
    return attributes;
  }


  public void setAttributes(Map<String, String> attributes) {
    this.attributes = attributes;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSnsConfigs httpConfig(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig httpConfig) {
    
    this.httpConfig = httpConfig;
    return this;
  }

   /**
   * Get httpConfig
   * @return httpConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig getHttpConfig() {
    return httpConfig;
  }


  public void setHttpConfig(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig httpConfig) {
    this.httpConfig = httpConfig;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSnsConfigs message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * The message content of the SNS notification.
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The message content of the SNS notification.")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSnsConfigs phoneNumber(String phoneNumber) {
    
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Phone number if message is delivered via SMS in E.164 format. If you don&#39;t specify this value, you must specify a value for the TopicARN or TargetARN.
   * @return phoneNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Phone number if message is delivered via SMS in E.164 format. If you don't specify this value, you must specify a value for the TopicARN or TargetARN.")

  public String getPhoneNumber() {
    return phoneNumber;
  }


  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSnsConfigs sendResolved(Boolean sendResolved) {
    
    this.sendResolved = sendResolved;
    return this;
  }

   /**
   * Whether or not to notify about resolved alerts.
   * @return sendResolved
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether or not to notify about resolved alerts.")

  public Boolean getSendResolved() {
    return sendResolved;
  }


  public void setSendResolved(Boolean sendResolved) {
    this.sendResolved = sendResolved;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSnsConfigs sigv4(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSigv4 sigv4) {
    
    this.sigv4 = sigv4;
    return this;
  }

   /**
   * Get sigv4
   * @return sigv4
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSigv4 getSigv4() {
    return sigv4;
  }


  public void setSigv4(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSigv4 sigv4) {
    this.sigv4 = sigv4;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSnsConfigs subject(String subject) {
    
    this.subject = subject;
    return this;
  }

   /**
   * Subject line when the message is delivered to email endpoints.
   * @return subject
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Subject line when the message is delivered to email endpoints.")

  public String getSubject() {
    return subject;
  }


  public void setSubject(String subject) {
    this.subject = subject;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSnsConfigs targetARN(String targetARN) {
    
    this.targetARN = targetARN;
    return this;
  }

   /**
   * The  mobile platform endpoint ARN if message is delivered via mobile notifications. If you don&#39;t specify this value, you must specify a value for the topic_arn or PhoneNumber.
   * @return targetARN
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The  mobile platform endpoint ARN if message is delivered via mobile notifications. If you don't specify this value, you must specify a value for the topic_arn or PhoneNumber.")

  public String getTargetARN() {
    return targetARN;
  }


  public void setTargetARN(String targetARN) {
    this.targetARN = targetARN;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSnsConfigs topicARN(String topicARN) {
    
    this.topicARN = topicARN;
    return this;
  }

   /**
   * SNS topic ARN, i.e. arn:aws:sns:us-east-2:698519295917:My-Topic If you don&#39;t specify this value, you must specify a value for the PhoneNumber or TargetARN.
   * @return topicARN
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "SNS topic ARN, i.e. arn:aws:sns:us-east-2:698519295917:My-Topic If you don't specify this value, you must specify a value for the PhoneNumber or TargetARN.")

  public String getTopicARN() {
    return topicARN;
  }


  public void setTopicARN(String topicARN) {
    this.topicARN = topicARN;
  }


  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSnsConfigs {\n");
    sb.append("    apiURL: ").append(toIndentedString(apiURL)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    httpConfig: ").append(toIndentedString(httpConfig)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    sendResolved: ").append(toIndentedString(sendResolved)).append("\n");
    sb.append("    sigv4: ").append(toIndentedString(sigv4)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    targetARN: ").append(toIndentedString(targetARN)).append("\n");
    sb.append("    topicARN: ").append(toIndentedString(topicARN)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

