/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.20.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.code.domain.k8s;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Selector to select which namespaces the Endpoints objects are discovered from.
 */
@ApiModel(description = "Selector to select which namespaces the Endpoints objects are discovered from.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-03T04:59:34.868Z[Etc/UTC]")
public class ComCoreosMonitoringV1PodMonitorSpecNamespaceSelector {
  public static final String SERIALIZED_NAME_ANY = "any";
  @SerializedName(SERIALIZED_NAME_ANY)
  private Boolean any;

  public static final String SERIALIZED_NAME_MATCH_NAMES = "matchNames";
  @SerializedName(SERIALIZED_NAME_MATCH_NAMES)
  private List<String> matchNames = null;


  public ComCoreosMonitoringV1PodMonitorSpecNamespaceSelector any(Boolean any) {
    
    this.any = any;
    return this;
  }

   /**
   * Boolean describing whether all namespaces are selected in contrast to a list restricting them.
   * @return any
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Boolean describing whether all namespaces are selected in contrast to a list restricting them.")

  public Boolean getAny() {
    return any;
  }


  public void setAny(Boolean any) {
    this.any = any;
  }


  public ComCoreosMonitoringV1PodMonitorSpecNamespaceSelector matchNames(List<String> matchNames) {
    
    this.matchNames = matchNames;
    return this;
  }

  public ComCoreosMonitoringV1PodMonitorSpecNamespaceSelector addMatchNamesItem(String matchNamesItem) {
    if (this.matchNames == null) {
      this.matchNames = new ArrayList<String>();
    }
    this.matchNames.add(matchNamesItem);
    return this;
  }

   /**
   * List of namespace names to select from.
   * @return matchNames
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of namespace names to select from.")

  public List<String> getMatchNames() {
    return matchNames;
  }


  public void setMatchNames(List<String> matchNames) {
    this.matchNames = matchNames;
  }


  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComCoreosMonitoringV1PodMonitorSpecNamespaceSelector {\n");
    sb.append("    any: ").append(toIndentedString(any)).append("\n");
    sb.append("    matchNames: ").append(toIndentedString(matchNames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

