/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.20.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.code.domain.k8s;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecApiKey1;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHeaders;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig1;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * VictorOpsConfig configures notifications via VictorOps. See https://prometheus.io/docs/alerting/latest/configuration/#victorops_config
 */
@ApiModel(description = "VictorOpsConfig configures notifications via VictorOps. See https://prometheus.io/docs/alerting/latest/configuration/#victorops_config")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-03T04:59:34.868Z[Etc/UTC]")
public class ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecVictoropsConfigs {
  public static final String SERIALIZED_NAME_API_KEY = "apiKey";
  @SerializedName(SERIALIZED_NAME_API_KEY)
  private ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecApiKey1 apiKey;

  public static final String SERIALIZED_NAME_API_URL = "apiUrl";
  @SerializedName(SERIALIZED_NAME_API_URL)
  private String apiUrl;

  public static final String SERIALIZED_NAME_CUSTOM_FIELDS = "customFields";
  @SerializedName(SERIALIZED_NAME_CUSTOM_FIELDS)
  private List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHeaders> customFields = null;

  public static final String SERIALIZED_NAME_ENTITY_DISPLAY_NAME = "entityDisplayName";
  @SerializedName(SERIALIZED_NAME_ENTITY_DISPLAY_NAME)
  private String entityDisplayName;

  public static final String SERIALIZED_NAME_HTTP_CONFIG = "httpConfig";
  @SerializedName(SERIALIZED_NAME_HTTP_CONFIG)
  private ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig1 httpConfig;

  public static final String SERIALIZED_NAME_MESSAGE_TYPE = "messageType";
  @SerializedName(SERIALIZED_NAME_MESSAGE_TYPE)
  private String messageType;

  public static final String SERIALIZED_NAME_MONITORING_TOOL = "monitoringTool";
  @SerializedName(SERIALIZED_NAME_MONITORING_TOOL)
  private String monitoringTool;

  public static final String SERIALIZED_NAME_ROUTING_KEY = "routingKey";
  @SerializedName(SERIALIZED_NAME_ROUTING_KEY)
  private String routingKey;

  public static final String SERIALIZED_NAME_SEND_RESOLVED = "sendResolved";
  @SerializedName(SERIALIZED_NAME_SEND_RESOLVED)
  private Boolean sendResolved;

  public static final String SERIALIZED_NAME_STATE_MESSAGE = "stateMessage";
  @SerializedName(SERIALIZED_NAME_STATE_MESSAGE)
  private String stateMessage;


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecVictoropsConfigs apiKey(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecApiKey1 apiKey) {
    
    this.apiKey = apiKey;
    return this;
  }

   /**
   * Get apiKey
   * @return apiKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecApiKey1 getApiKey() {
    return apiKey;
  }


  public void setApiKey(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecApiKey1 apiKey) {
    this.apiKey = apiKey;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecVictoropsConfigs apiUrl(String apiUrl) {
    
    this.apiUrl = apiUrl;
    return this;
  }

   /**
   * The VictorOps API URL.
   * @return apiUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The VictorOps API URL.")

  public String getApiUrl() {
    return apiUrl;
  }


  public void setApiUrl(String apiUrl) {
    this.apiUrl = apiUrl;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecVictoropsConfigs customFields(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHeaders> customFields) {
    
    this.customFields = customFields;
    return this;
  }

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecVictoropsConfigs addCustomFieldsItem(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHeaders customFieldsItem) {
    if (this.customFields == null) {
      this.customFields = new ArrayList<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHeaders>();
    }
    this.customFields.add(customFieldsItem);
    return this;
  }

   /**
   * Additional custom fields for notification.
   * @return customFields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Additional custom fields for notification.")

  public List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHeaders> getCustomFields() {
    return customFields;
  }


  public void setCustomFields(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHeaders> customFields) {
    this.customFields = customFields;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecVictoropsConfigs entityDisplayName(String entityDisplayName) {
    
    this.entityDisplayName = entityDisplayName;
    return this;
  }

   /**
   * Contains summary of the alerted problem.
   * @return entityDisplayName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Contains summary of the alerted problem.")

  public String getEntityDisplayName() {
    return entityDisplayName;
  }


  public void setEntityDisplayName(String entityDisplayName) {
    this.entityDisplayName = entityDisplayName;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecVictoropsConfigs httpConfig(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig1 httpConfig) {
    
    this.httpConfig = httpConfig;
    return this;
  }

   /**
   * Get httpConfig
   * @return httpConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig1 getHttpConfig() {
    return httpConfig;
  }


  public void setHttpConfig(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig1 httpConfig) {
    this.httpConfig = httpConfig;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecVictoropsConfigs messageType(String messageType) {
    
    this.messageType = messageType;
    return this;
  }

   /**
   * Describes the behavior of the alert (CRITICAL, WARNING, INFO).
   * @return messageType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Describes the behavior of the alert (CRITICAL, WARNING, INFO).")

  public String getMessageType() {
    return messageType;
  }


  public void setMessageType(String messageType) {
    this.messageType = messageType;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecVictoropsConfigs monitoringTool(String monitoringTool) {
    
    this.monitoringTool = monitoringTool;
    return this;
  }

   /**
   * The monitoring tool the state message is from.
   * @return monitoringTool
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The monitoring tool the state message is from.")

  public String getMonitoringTool() {
    return monitoringTool;
  }


  public void setMonitoringTool(String monitoringTool) {
    this.monitoringTool = monitoringTool;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecVictoropsConfigs routingKey(String routingKey) {
    
    this.routingKey = routingKey;
    return this;
  }

   /**
   * A key used to map the alert to a team.
   * @return routingKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A key used to map the alert to a team.")

  public String getRoutingKey() {
    return routingKey;
  }


  public void setRoutingKey(String routingKey) {
    this.routingKey = routingKey;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecVictoropsConfigs sendResolved(Boolean sendResolved) {
    
    this.sendResolved = sendResolved;
    return this;
  }

   /**
   * Whether or not to notify about resolved alerts.
   * @return sendResolved
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether or not to notify about resolved alerts.")

  public Boolean getSendResolved() {
    return sendResolved;
  }


  public void setSendResolved(Boolean sendResolved) {
    this.sendResolved = sendResolved;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecVictoropsConfigs stateMessage(String stateMessage) {
    
    this.stateMessage = stateMessage;
    return this;
  }

   /**
   * Contains long explanation of the alerted problem.
   * @return stateMessage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Contains long explanation of the alerted problem.")

  public String getStateMessage() {
    return stateMessage;
  }


  public void setStateMessage(String stateMessage) {
    this.stateMessage = stateMessage;
  }


  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecVictoropsConfigs {\n");
    sb.append("    apiKey: ").append(toIndentedString(apiKey)).append("\n");
    sb.append("    apiUrl: ").append(toIndentedString(apiUrl)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    entityDisplayName: ").append(toIndentedString(entityDisplayName)).append("\n");
    sb.append("    httpConfig: ").append(toIndentedString(httpConfig)).append("\n");
    sb.append("    messageType: ").append(toIndentedString(messageType)).append("\n");
    sb.append("    monitoringTool: ").append(toIndentedString(monitoringTool)).append("\n");
    sb.append("    routingKey: ").append(toIndentedString(routingKey)).append("\n");
    sb.append("    sendResolved: ").append(toIndentedString(sendResolved)).append("\n");
    sb.append("    stateMessage: ").append(toIndentedString(stateMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

