/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.20.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.code.domain.k8s;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.example.code.domain.k8s.ComCoreosMonitoringV1PrometheusRuleSpecRules;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * RuleGroup is a list of sequentially evaluated recording and alerting rules. Note: PartialResponseStrategy is only used by ThanosRuler and will be ignored by Prometheus instances.  Valid values for this field are &#39;warn&#39; or &#39;abort&#39;.  More info: https://github.com/thanos-io/thanos/blob/main/docs/components/rule.md#partial-response
 */
@ApiModel(description = "RuleGroup is a list of sequentially evaluated recording and alerting rules. Note: PartialResponseStrategy is only used by ThanosRuler and will be ignored by Prometheus instances.  Valid values for this field are 'warn' or 'abort'.  More info: https://github.com/thanos-io/thanos/blob/main/docs/components/rule.md#partial-response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-03T04:59:34.868Z[Etc/UTC]")
public class ComCoreosMonitoringV1PrometheusRuleSpecGroups {
  public static final String SERIALIZED_NAME_INTERVAL = "interval";
  @SerializedName(SERIALIZED_NAME_INTERVAL)
  private String interval;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PARTIAL_RESPONSE_STRATEGY = "partial_response_strategy";
  @SerializedName(SERIALIZED_NAME_PARTIAL_RESPONSE_STRATEGY)
  private String partialResponseStrategy;

  public static final String SERIALIZED_NAME_RULES = "rules";
  @SerializedName(SERIALIZED_NAME_RULES)
  private List<ComCoreosMonitoringV1PrometheusRuleSpecRules> rules = new ArrayList<ComCoreosMonitoringV1PrometheusRuleSpecRules>();


  public ComCoreosMonitoringV1PrometheusRuleSpecGroups interval(String interval) {
    
    this.interval = interval;
    return this;
  }

   /**
   * Get interval
   * @return interval
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getInterval() {
    return interval;
  }


  public void setInterval(String interval) {
    this.interval = interval;
  }


  public ComCoreosMonitoringV1PrometheusRuleSpecGroups name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ComCoreosMonitoringV1PrometheusRuleSpecGroups partialResponseStrategy(String partialResponseStrategy) {
    
    this.partialResponseStrategy = partialResponseStrategy;
    return this;
  }

   /**
   * Get partialResponseStrategy
   * @return partialResponseStrategy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPartialResponseStrategy() {
    return partialResponseStrategy;
  }


  public void setPartialResponseStrategy(String partialResponseStrategy) {
    this.partialResponseStrategy = partialResponseStrategy;
  }


  public ComCoreosMonitoringV1PrometheusRuleSpecGroups rules(List<ComCoreosMonitoringV1PrometheusRuleSpecRules> rules) {
    
    this.rules = rules;
    return this;
  }

  public ComCoreosMonitoringV1PrometheusRuleSpecGroups addRulesItem(ComCoreosMonitoringV1PrometheusRuleSpecRules rulesItem) {
    this.rules.add(rulesItem);
    return this;
  }

   /**
   * Get rules
   * @return rules
  **/
  @ApiModelProperty(required = true, value = "")

  public List<ComCoreosMonitoringV1PrometheusRuleSpecRules> getRules() {
    return rules;
  }


  public void setRules(List<ComCoreosMonitoringV1PrometheusRuleSpecRules> rules) {
    this.rules = rules;
  }


  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComCoreosMonitoringV1PrometheusRuleSpecGroups {\n");
    sb.append("    interval: ").append(toIndentedString(interval)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    partialResponseStrategy: ").append(toIndentedString(partialResponseStrategy)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

