/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.20.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.code.domain.k8s;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSourceMatch;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * The Alertmanager route definition for alerts matching the resource’s namespace. If present, it will be added to the generated Alertmanager configuration as a first-level route.
 */
@ApiModel(description = "The Alertmanager route definition for alerts matching the resource’s namespace. If present, it will be added to the generated Alertmanager configuration as a first-level route.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-03T04:59:34.868Z[Etc/UTC]")
public class ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecRoute {
  public static final String SERIALIZED_NAME_CONTINUE = "continue";
  @SerializedName(SERIALIZED_NAME_CONTINUE)
  private Boolean _continue;

  public static final String SERIALIZED_NAME_GROUP_BY = "groupBy";
  @SerializedName(SERIALIZED_NAME_GROUP_BY)
  private List<String> groupBy = null;

  public static final String SERIALIZED_NAME_GROUP_INTERVAL = "groupInterval";
  @SerializedName(SERIALIZED_NAME_GROUP_INTERVAL)
  private String groupInterval;

  public static final String SERIALIZED_NAME_GROUP_WAIT = "groupWait";
  @SerializedName(SERIALIZED_NAME_GROUP_WAIT)
  private String groupWait;

  public static final String SERIALIZED_NAME_MATCHERS = "matchers";
  @SerializedName(SERIALIZED_NAME_MATCHERS)
  private List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSourceMatch> matchers = null;

  public static final String SERIALIZED_NAME_MUTE_TIME_INTERVALS = "muteTimeIntervals";
  @SerializedName(SERIALIZED_NAME_MUTE_TIME_INTERVALS)
  private List<String> muteTimeIntervals = null;

  public static final String SERIALIZED_NAME_RECEIVER = "receiver";
  @SerializedName(SERIALIZED_NAME_RECEIVER)
  private String receiver;

  public static final String SERIALIZED_NAME_REPEAT_INTERVAL = "repeatInterval";
  @SerializedName(SERIALIZED_NAME_REPEAT_INTERVAL)
  private String repeatInterval;

  public static final String SERIALIZED_NAME_ROUTES = "routes";
  @SerializedName(SERIALIZED_NAME_ROUTES)
  private List<Object> routes = null;


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecRoute _continue(Boolean _continue) {
    
    this._continue = _continue;
    return this;
  }

   /**
   * Boolean indicating whether an alert should continue matching subsequent sibling nodes. It will always be overridden to true for the first-level route by the Prometheus operator.
   * @return _continue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Boolean indicating whether an alert should continue matching subsequent sibling nodes. It will always be overridden to true for the first-level route by the Prometheus operator.")

  public Boolean getContinue() {
    return _continue;
  }


  public void setContinue(Boolean _continue) {
    this._continue = _continue;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecRoute groupBy(List<String> groupBy) {
    
    this.groupBy = groupBy;
    return this;
  }

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecRoute addGroupByItem(String groupByItem) {
    if (this.groupBy == null) {
      this.groupBy = new ArrayList<String>();
    }
    this.groupBy.add(groupByItem);
    return this;
  }

   /**
   * List of labels to group by. Labels must not be repeated (unique list). Special label \&quot;...\&quot; (aggregate by all possible labels), if provided, must be the only element in the list.
   * @return groupBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of labels to group by. Labels must not be repeated (unique list). Special label \"...\" (aggregate by all possible labels), if provided, must be the only element in the list.")

  public List<String> getGroupBy() {
    return groupBy;
  }


  public void setGroupBy(List<String> groupBy) {
    this.groupBy = groupBy;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecRoute groupInterval(String groupInterval) {
    
    this.groupInterval = groupInterval;
    return this;
  }

   /**
   * How long to wait before sending an updated notification. Must match the regular expression&#x60;^(([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?$&#x60; Example: \&quot;5m\&quot;
   * @return groupInterval
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "How long to wait before sending an updated notification. Must match the regular expression`^(([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?$` Example: \"5m\"")

  public String getGroupInterval() {
    return groupInterval;
  }


  public void setGroupInterval(String groupInterval) {
    this.groupInterval = groupInterval;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecRoute groupWait(String groupWait) {
    
    this.groupWait = groupWait;
    return this;
  }

   /**
   * How long to wait before sending the initial notification. Must match the regular expression&#x60;^(([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?$&#x60; Example: \&quot;30s\&quot;
   * @return groupWait
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "How long to wait before sending the initial notification. Must match the regular expression`^(([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?$` Example: \"30s\"")

  public String getGroupWait() {
    return groupWait;
  }


  public void setGroupWait(String groupWait) {
    this.groupWait = groupWait;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecRoute matchers(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSourceMatch> matchers) {
    
    this.matchers = matchers;
    return this;
  }

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecRoute addMatchersItem(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSourceMatch matchersItem) {
    if (this.matchers == null) {
      this.matchers = new ArrayList<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSourceMatch>();
    }
    this.matchers.add(matchersItem);
    return this;
  }

   /**
   * List of matchers that the alert’s labels should match. For the first level route, the operator removes any existing equality and regexp matcher on the &#x60;namespace&#x60; label and adds a &#x60;namespace: &lt;object namespace&gt;&#x60; matcher.
   * @return matchers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of matchers that the alert’s labels should match. For the first level route, the operator removes any existing equality and regexp matcher on the `namespace` label and adds a `namespace: <object namespace>` matcher.")

  public List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSourceMatch> getMatchers() {
    return matchers;
  }


  public void setMatchers(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSourceMatch> matchers) {
    this.matchers = matchers;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecRoute muteTimeIntervals(List<String> muteTimeIntervals) {
    
    this.muteTimeIntervals = muteTimeIntervals;
    return this;
  }

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecRoute addMuteTimeIntervalsItem(String muteTimeIntervalsItem) {
    if (this.muteTimeIntervals == null) {
      this.muteTimeIntervals = new ArrayList<String>();
    }
    this.muteTimeIntervals.add(muteTimeIntervalsItem);
    return this;
  }

   /**
   * Note: this comment applies to the field definition above but appears below otherwise it gets included in the generated manifest. CRD schema doesn&#39;t support self-referential types for now (see https://github.com/kubernetes/kubernetes/issues/62872). We have to use an alternative type to circumvent the limitation. The downside is that the Kube API can&#39;t validate the data beyond the fact that it is a valid JSON representation. MuteTimeIntervals is a list of MuteTimeInterval names that will mute this route when matched,
   * @return muteTimeIntervals
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Note: this comment applies to the field definition above but appears below otherwise it gets included in the generated manifest. CRD schema doesn't support self-referential types for now (see https://github.com/kubernetes/kubernetes/issues/62872). We have to use an alternative type to circumvent the limitation. The downside is that the Kube API can't validate the data beyond the fact that it is a valid JSON representation. MuteTimeIntervals is a list of MuteTimeInterval names that will mute this route when matched,")

  public List<String> getMuteTimeIntervals() {
    return muteTimeIntervals;
  }


  public void setMuteTimeIntervals(List<String> muteTimeIntervals) {
    this.muteTimeIntervals = muteTimeIntervals;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecRoute receiver(String receiver) {
    
    this.receiver = receiver;
    return this;
  }

   /**
   * Name of the receiver for this route. If not empty, it should be listed in the &#x60;receivers&#x60; field.
   * @return receiver
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the receiver for this route. If not empty, it should be listed in the `receivers` field.")

  public String getReceiver() {
    return receiver;
  }


  public void setReceiver(String receiver) {
    this.receiver = receiver;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecRoute repeatInterval(String repeatInterval) {
    
    this.repeatInterval = repeatInterval;
    return this;
  }

   /**
   * How long to wait before repeating the last notification. Must match the regular expression&#x60;^(([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?$&#x60; Example: \&quot;4h\&quot;
   * @return repeatInterval
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "How long to wait before repeating the last notification. Must match the regular expression`^(([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?$` Example: \"4h\"")

  public String getRepeatInterval() {
    return repeatInterval;
  }


  public void setRepeatInterval(String repeatInterval) {
    this.repeatInterval = repeatInterval;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecRoute routes(List<Object> routes) {
    
    this.routes = routes;
    return this;
  }

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecRoute addRoutesItem(Object routesItem) {
    if (this.routes == null) {
      this.routes = new ArrayList<Object>();
    }
    this.routes.add(routesItem);
    return this;
  }

   /**
   * Child routes.
   * @return routes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Child routes.")

  public List<Object> getRoutes() {
    return routes;
  }


  public void setRoutes(List<Object> routes) {
    this.routes = routes;
  }


  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecRoute {\n");
    sb.append("    _continue: ").append(toIndentedString(_continue)).append("\n");
    sb.append("    groupBy: ").append(toIndentedString(groupBy)).append("\n");
    sb.append("    groupInterval: ").append(toIndentedString(groupInterval)).append("\n");
    sb.append("    groupWait: ").append(toIndentedString(groupWait)).append("\n");
    sb.append("    matchers: ").append(toIndentedString(matchers)).append("\n");
    sb.append("    muteTimeIntervals: ").append(toIndentedString(muteTimeIntervals)).append("\n");
    sb.append("    receiver: ").append(toIndentedString(receiver)).append("\n");
    sb.append("    repeatInterval: ").append(toIndentedString(repeatInterval)).append("\n");
    sb.append("    routes: ").append(toIndentedString(routes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

