/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.20.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.code.domain.k8s;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecActions;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecApiURL;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecFields;
import com.example.code.domain.k8s.ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SlackConfig configures notifications via Slack. See https://prometheus.io/docs/alerting/latest/configuration/#slack_config
 */
@ApiModel(description = "SlackConfig configures notifications via Slack. See https://prometheus.io/docs/alerting/latest/configuration/#slack_config")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-03T04:59:34.868Z[Etc/UTC]")
public class ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs {
  public static final String SERIALIZED_NAME_ACTIONS = "actions";
  @SerializedName(SERIALIZED_NAME_ACTIONS)
  private List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecActions> actions = null;

  public static final String SERIALIZED_NAME_API_U_R_L = "apiURL";
  @SerializedName(SERIALIZED_NAME_API_U_R_L)
  private ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecApiURL apiURL;

  public static final String SERIALIZED_NAME_CALLBACK_ID = "callbackId";
  @SerializedName(SERIALIZED_NAME_CALLBACK_ID)
  private String callbackId;

  public static final String SERIALIZED_NAME_CHANNEL = "channel";
  @SerializedName(SERIALIZED_NAME_CHANNEL)
  private String channel;

  public static final String SERIALIZED_NAME_COLOR = "color";
  @SerializedName(SERIALIZED_NAME_COLOR)
  private String color;

  public static final String SERIALIZED_NAME_FALLBACK = "fallback";
  @SerializedName(SERIALIZED_NAME_FALLBACK)
  private String fallback;

  public static final String SERIALIZED_NAME_FIELDS = "fields";
  @SerializedName(SERIALIZED_NAME_FIELDS)
  private List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecFields> fields = null;

  public static final String SERIALIZED_NAME_FOOTER = "footer";
  @SerializedName(SERIALIZED_NAME_FOOTER)
  private String footer;

  public static final String SERIALIZED_NAME_HTTP_CONFIG = "httpConfig";
  @SerializedName(SERIALIZED_NAME_HTTP_CONFIG)
  private ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig httpConfig;

  public static final String SERIALIZED_NAME_ICON_EMOJI = "iconEmoji";
  @SerializedName(SERIALIZED_NAME_ICON_EMOJI)
  private String iconEmoji;

  public static final String SERIALIZED_NAME_ICON_U_R_L = "iconURL";
  @SerializedName(SERIALIZED_NAME_ICON_U_R_L)
  private String iconURL;

  public static final String SERIALIZED_NAME_IMAGE_U_R_L = "imageURL";
  @SerializedName(SERIALIZED_NAME_IMAGE_U_R_L)
  private String imageURL;

  public static final String SERIALIZED_NAME_LINK_NAMES = "linkNames";
  @SerializedName(SERIALIZED_NAME_LINK_NAMES)
  private Boolean linkNames;

  public static final String SERIALIZED_NAME_MRKDWN_IN = "mrkdwnIn";
  @SerializedName(SERIALIZED_NAME_MRKDWN_IN)
  private List<String> mrkdwnIn = null;

  public static final String SERIALIZED_NAME_PRETEXT = "pretext";
  @SerializedName(SERIALIZED_NAME_PRETEXT)
  private String pretext;

  public static final String SERIALIZED_NAME_SEND_RESOLVED = "sendResolved";
  @SerializedName(SERIALIZED_NAME_SEND_RESOLVED)
  private Boolean sendResolved;

  public static final String SERIALIZED_NAME_SHORT_FIELDS = "shortFields";
  @SerializedName(SERIALIZED_NAME_SHORT_FIELDS)
  private Boolean shortFields;

  public static final String SERIALIZED_NAME_TEXT = "text";
  @SerializedName(SERIALIZED_NAME_TEXT)
  private String text;

  public static final String SERIALIZED_NAME_THUMB_U_R_L = "thumbURL";
  @SerializedName(SERIALIZED_NAME_THUMB_U_R_L)
  private String thumbURL;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_TITLE_LINK = "titleLink";
  @SerializedName(SERIALIZED_NAME_TITLE_LINK)
  private String titleLink;

  public static final String SERIALIZED_NAME_USERNAME = "username";
  @SerializedName(SERIALIZED_NAME_USERNAME)
  private String username;


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs actions(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecActions> actions) {
    
    this.actions = actions;
    return this;
  }

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs addActionsItem(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecActions actionsItem) {
    if (this.actions == null) {
      this.actions = new ArrayList<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecActions>();
    }
    this.actions.add(actionsItem);
    return this;
  }

   /**
   * A list of Slack actions that are sent with each notification.
   * @return actions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of Slack actions that are sent with each notification.")

  public List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecActions> getActions() {
    return actions;
  }


  public void setActions(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecActions> actions) {
    this.actions = actions;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs apiURL(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecApiURL apiURL) {
    
    this.apiURL = apiURL;
    return this;
  }

   /**
   * Get apiURL
   * @return apiURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecApiURL getApiURL() {
    return apiURL;
  }


  public void setApiURL(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecApiURL apiURL) {
    this.apiURL = apiURL;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs callbackId(String callbackId) {
    
    this.callbackId = callbackId;
    return this;
  }

   /**
   * Get callbackId
   * @return callbackId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCallbackId() {
    return callbackId;
  }


  public void setCallbackId(String callbackId) {
    this.callbackId = callbackId;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs channel(String channel) {
    
    this.channel = channel;
    return this;
  }

   /**
   * The channel or user to send notifications to.
   * @return channel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The channel or user to send notifications to.")

  public String getChannel() {
    return channel;
  }


  public void setChannel(String channel) {
    this.channel = channel;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs color(String color) {
    
    this.color = color;
    return this;
  }

   /**
   * Get color
   * @return color
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getColor() {
    return color;
  }


  public void setColor(String color) {
    this.color = color;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs fallback(String fallback) {
    
    this.fallback = fallback;
    return this;
  }

   /**
   * Get fallback
   * @return fallback
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFallback() {
    return fallback;
  }


  public void setFallback(String fallback) {
    this.fallback = fallback;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs fields(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecFields> fields) {
    
    this.fields = fields;
    return this;
  }

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs addFieldsItem(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecFields fieldsItem) {
    if (this.fields == null) {
      this.fields = new ArrayList<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecFields>();
    }
    this.fields.add(fieldsItem);
    return this;
  }

   /**
   * A list of Slack fields that are sent with each notification.
   * @return fields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of Slack fields that are sent with each notification.")

  public List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecFields> getFields() {
    return fields;
  }


  public void setFields(List<ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecFields> fields) {
    this.fields = fields;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs footer(String footer) {
    
    this.footer = footer;
    return this;
  }

   /**
   * Get footer
   * @return footer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFooter() {
    return footer;
  }


  public void setFooter(String footer) {
    this.footer = footer;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs httpConfig(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig httpConfig) {
    
    this.httpConfig = httpConfig;
    return this;
  }

   /**
   * Get httpConfig
   * @return httpConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig getHttpConfig() {
    return httpConfig;
  }


  public void setHttpConfig(ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecHttpConfig httpConfig) {
    this.httpConfig = httpConfig;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs iconEmoji(String iconEmoji) {
    
    this.iconEmoji = iconEmoji;
    return this;
  }

   /**
   * Get iconEmoji
   * @return iconEmoji
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIconEmoji() {
    return iconEmoji;
  }


  public void setIconEmoji(String iconEmoji) {
    this.iconEmoji = iconEmoji;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs iconURL(String iconURL) {
    
    this.iconURL = iconURL;
    return this;
  }

   /**
   * Get iconURL
   * @return iconURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIconURL() {
    return iconURL;
  }


  public void setIconURL(String iconURL) {
    this.iconURL = iconURL;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs imageURL(String imageURL) {
    
    this.imageURL = imageURL;
    return this;
  }

   /**
   * Get imageURL
   * @return imageURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getImageURL() {
    return imageURL;
  }


  public void setImageURL(String imageURL) {
    this.imageURL = imageURL;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs linkNames(Boolean linkNames) {
    
    this.linkNames = linkNames;
    return this;
  }

   /**
   * Get linkNames
   * @return linkNames
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getLinkNames() {
    return linkNames;
  }


  public void setLinkNames(Boolean linkNames) {
    this.linkNames = linkNames;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs mrkdwnIn(List<String> mrkdwnIn) {
    
    this.mrkdwnIn = mrkdwnIn;
    return this;
  }

  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs addMrkdwnInItem(String mrkdwnInItem) {
    if (this.mrkdwnIn == null) {
      this.mrkdwnIn = new ArrayList<String>();
    }
    this.mrkdwnIn.add(mrkdwnInItem);
    return this;
  }

   /**
   * Get mrkdwnIn
   * @return mrkdwnIn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getMrkdwnIn() {
    return mrkdwnIn;
  }


  public void setMrkdwnIn(List<String> mrkdwnIn) {
    this.mrkdwnIn = mrkdwnIn;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs pretext(String pretext) {
    
    this.pretext = pretext;
    return this;
  }

   /**
   * Get pretext
   * @return pretext
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPretext() {
    return pretext;
  }


  public void setPretext(String pretext) {
    this.pretext = pretext;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs sendResolved(Boolean sendResolved) {
    
    this.sendResolved = sendResolved;
    return this;
  }

   /**
   * Whether or not to notify about resolved alerts.
   * @return sendResolved
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether or not to notify about resolved alerts.")

  public Boolean getSendResolved() {
    return sendResolved;
  }


  public void setSendResolved(Boolean sendResolved) {
    this.sendResolved = sendResolved;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs shortFields(Boolean shortFields) {
    
    this.shortFields = shortFields;
    return this;
  }

   /**
   * Get shortFields
   * @return shortFields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getShortFields() {
    return shortFields;
  }


  public void setShortFields(Boolean shortFields) {
    this.shortFields = shortFields;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs text(String text) {
    
    this.text = text;
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getText() {
    return text;
  }


  public void setText(String text) {
    this.text = text;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs thumbURL(String thumbURL) {
    
    this.thumbURL = thumbURL;
    return this;
  }

   /**
   * Get thumbURL
   * @return thumbURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getThumbURL() {
    return thumbURL;
  }


  public void setThumbURL(String thumbURL) {
    this.thumbURL = thumbURL;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs titleLink(String titleLink) {
    
    this.titleLink = titleLink;
    return this;
  }

   /**
   * Get titleLink
   * @return titleLink
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTitleLink() {
    return titleLink;
  }


  public void setTitleLink(String titleLink) {
    this.titleLink = titleLink;
  }


  public ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs username(String username) {
    
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUsername() {
    return username;
  }


  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecSlackConfigs {\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    apiURL: ").append(toIndentedString(apiURL)).append("\n");
    sb.append("    callbackId: ").append(toIndentedString(callbackId)).append("\n");
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    fallback: ").append(toIndentedString(fallback)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    footer: ").append(toIndentedString(footer)).append("\n");
    sb.append("    httpConfig: ").append(toIndentedString(httpConfig)).append("\n");
    sb.append("    iconEmoji: ").append(toIndentedString(iconEmoji)).append("\n");
    sb.append("    iconURL: ").append(toIndentedString(iconURL)).append("\n");
    sb.append("    imageURL: ").append(toIndentedString(imageURL)).append("\n");
    sb.append("    linkNames: ").append(toIndentedString(linkNames)).append("\n");
    sb.append("    mrkdwnIn: ").append(toIndentedString(mrkdwnIn)).append("\n");
    sb.append("    pretext: ").append(toIndentedString(pretext)).append("\n");
    sb.append("    sendResolved: ").append(toIndentedString(sendResolved)).append("\n");
    sb.append("    shortFields: ").append(toIndentedString(shortFields)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    thumbURL: ").append(toIndentedString(thumbURL)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    titleLink: ").append(toIndentedString(titleLink)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

