/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.20.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.code.domain.k8s;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.example.code.domain.k8s.ComCoreosMonitoringV1ProbeSpecTargetsIngress;
import com.example.code.domain.k8s.ComCoreosMonitoringV1ProbeSpecTargetsStaticConfig;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Targets defines a set of static or dynamically discovered targets to probe.
 */
@ApiModel(description = "Targets defines a set of static or dynamically discovered targets to probe.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-03T04:59:34.868Z[Etc/UTC]")
public class ComCoreosMonitoringV1ProbeSpecTargets {
  public static final String SERIALIZED_NAME_INGRESS = "ingress";
  @SerializedName(SERIALIZED_NAME_INGRESS)
  private ComCoreosMonitoringV1ProbeSpecTargetsIngress ingress;

  public static final String SERIALIZED_NAME_STATIC_CONFIG = "staticConfig";
  @SerializedName(SERIALIZED_NAME_STATIC_CONFIG)
  private ComCoreosMonitoringV1ProbeSpecTargetsStaticConfig staticConfig;


  public ComCoreosMonitoringV1ProbeSpecTargets ingress(ComCoreosMonitoringV1ProbeSpecTargetsIngress ingress) {
    
    this.ingress = ingress;
    return this;
  }

   /**
   * Get ingress
   * @return ingress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ComCoreosMonitoringV1ProbeSpecTargetsIngress getIngress() {
    return ingress;
  }


  public void setIngress(ComCoreosMonitoringV1ProbeSpecTargetsIngress ingress) {
    this.ingress = ingress;
  }


  public ComCoreosMonitoringV1ProbeSpecTargets staticConfig(ComCoreosMonitoringV1ProbeSpecTargetsStaticConfig staticConfig) {
    
    this.staticConfig = staticConfig;
    return this;
  }

   /**
   * Get staticConfig
   * @return staticConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ComCoreosMonitoringV1ProbeSpecTargetsStaticConfig getStaticConfig() {
    return staticConfig;
  }


  public void setStaticConfig(ComCoreosMonitoringV1ProbeSpecTargetsStaticConfig staticConfig) {
    this.staticConfig = staticConfig;
  }


  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComCoreosMonitoringV1ProbeSpecTargets {\n");
    sb.append("    ingress: ").append(toIndentedString(ingress)).append("\n");
    sb.append("    staticConfig: ").append(toIndentedString(staticConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

