/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.20.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.code.domain.k8s;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AutoScalerStatus defines the observed state of AutoScaler
 */
@ApiModel(description = "AutoScalerStatus defines the observed state of AutoScaler")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-03T04:59:34.868Z[Etc/UTC]")
public class DomainGpugroupGpugroupV1AutoScalerStatus {
  public static final String SERIALIZED_NAME_MSG = "msg";
  @SerializedName(SERIALIZED_NAME_MSG)
  private String msg;

  public static final String SERIALIZED_NAME_PHASE = "phase";
  @SerializedName(SERIALIZED_NAME_PHASE)
  private String phase;

  public static final String SERIALIZED_NAME_PODS_FAILED = "podsFailed";
  @SerializedName(SERIALIZED_NAME_PODS_FAILED)
  private List<String> podsFailed = null;

  public static final String SERIALIZED_NAME_PODS_SUCCEED = "podsSucceed";
  @SerializedName(SERIALIZED_NAME_PODS_SUCCEED)
  private List<String> podsSucceed = null;

  public static final String SERIALIZED_NAME_SERVICE = "service";
  @SerializedName(SERIALIZED_NAME_SERVICE)
  private String service;


  public DomainGpugroupGpugroupV1AutoScalerStatus msg(String msg) {
    
    this.msg = msg;
    return this;
  }

   /**
   * Get msg
   * @return msg
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMsg() {
    return msg;
  }


  public void setMsg(String msg) {
    this.msg = msg;
  }


  public DomainGpugroupGpugroupV1AutoScalerStatus phase(String phase) {
    
    this.phase = phase;
    return this;
  }

   /**
   * Get phase
   * @return phase
  **/
  @ApiModelProperty(required = true, value = "")

  public String getPhase() {
    return phase;
  }


  public void setPhase(String phase) {
    this.phase = phase;
  }


  public DomainGpugroupGpugroupV1AutoScalerStatus podsFailed(List<String> podsFailed) {
    
    this.podsFailed = podsFailed;
    return this;
  }

  public DomainGpugroupGpugroupV1AutoScalerStatus addPodsFailedItem(String podsFailedItem) {
    if (this.podsFailed == null) {
      this.podsFailed = new ArrayList<String>();
    }
    this.podsFailed.add(podsFailedItem);
    return this;
  }

   /**
   * Get podsFailed
   * @return podsFailed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getPodsFailed() {
    return podsFailed;
  }


  public void setPodsFailed(List<String> podsFailed) {
    this.podsFailed = podsFailed;
  }


  public DomainGpugroupGpugroupV1AutoScalerStatus podsSucceed(List<String> podsSucceed) {
    
    this.podsSucceed = podsSucceed;
    return this;
  }

  public DomainGpugroupGpugroupV1AutoScalerStatus addPodsSucceedItem(String podsSucceedItem) {
    if (this.podsSucceed == null) {
      this.podsSucceed = new ArrayList<String>();
    }
    this.podsSucceed.add(podsSucceedItem);
    return this;
  }

   /**
   * Get podsSucceed
   * @return podsSucceed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getPodsSucceed() {
    return podsSucceed;
  }


  public void setPodsSucceed(List<String> podsSucceed) {
    this.podsSucceed = podsSucceed;
  }


  public DomainGpugroupGpugroupV1AutoScalerStatus service(String service) {
    
    this.service = service;
    return this;
  }

   /**
   * Get service
   * @return service
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getService() {
    return service;
  }


  public void setService(String service) {
    this.service = service;
  }


  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DomainGpugroupGpugroupV1AutoScalerStatus {\n");
    sb.append("    msg: ").append(toIndentedString(msg)).append("\n");
    sb.append("    phase: ").append(toIndentedString(phase)).append("\n");
    sb.append("    podsFailed: ").append(toIndentedString(podsFailed)).append("\n");
    sb.append("    podsSucceed: ").append(toIndentedString(podsSucceed)).append("\n");
    sb.append("    service: ").append(toIndentedString(service)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

